/**
 * Matchstatistik Hammarby–GAIS 2–0, omgång 18.
 * Källa: Bolldata match-API (id 7339) + Twelve match report 23/24 aug 2026.
 * Första halvlek kompletterad med FotMob 1H-stat.
 */
export const gaisRound18PartialMatchData = {
  gameweek: 18,
  date: "2026-08-23",
  matchName: "Hammarby - GAIS, 2-0",
  hammarby: {
    goals: 2,
    possessionPercent: 66,
    xg: 3.0,
    shots: 26,
    shotsOnTarget: 7,
    touchesInOppositionBox: 37,
    bigChances: 6,
    bigChancesMissed: 4,
    accuratePasses: 592,
    passAccuracyPercent: 88,
    fouls: 11,
    offsides: 0,
    corners: 8,
  },
  opponent: {
    teamName: "GAIS",
    goals: 0,
    possessionPercent: 34,
    xg: 1.01,
    shots: 9,
    shotsOnTarget: 1,
    touchesInOppositionBox: 7,
    bigChances: 3,
    bigChancesMissed: 3,
    accuratePasses: 264,
    passAccuracyPercent: 77,
    fouls: 18,
    offsides: 2,
    corners: 1,
  },
  firstHalf: {
    source: "FotMob 1H",
    hammarby: {
      possessionPercent: 74,
      xg: 1.78,
      shots: 21,
      shotsOnTarget: 6,
      touchesInOppositionBox: 28,
      bigChances: 2,
      bigChancesMissed: 1,
      accuratePasses: 329,
      passAccuracyPercent: 89,
      fouls: 3,
      offsides: 0,
      corners: 5,
    },
    opponent: {
      possessionPercent: 26,
      xg: 0.12,
      shots: 2,
      shotsOnTarget: 0,
      touchesInOppositionBox: 6,
      bigChances: 0,
      bigChancesMissed: 0,
      accuratePasses: 89,
      passAccuracyPercent: 68,
      fouls: 9,
      offsides: 1,
      corners: 0,
    },
  },
} as const;
