export interface PlayerTrendMetrics {
  passes: number;
  passAccuracy: number;
  forwardPasses: number;
  forwardPassAccuracy: number;
  passesToFinalThird: number;
  finalThirdPassAccuracy: number;
  keyPasses: number;
  xA: number;
  shots: number;
  shotsOnTarget: number;
  xG: number;
  touchesInBox: number;
  dribbles: number;
  dribbleSuccess: number;
  defensiveDuels: number;
  defensiveDuelWinRate: number;
  aerialDuels: number;
  aerialDuelWinRate: number;
  recoveries: number;
}

export interface PlayerTrendMatchPlayer {
  playerId: number;
  playerName: string;
  roleName: string;
  minutes: number;
  metrics: PlayerTrendMetrics;
}

export interface PlayerTrendMatch {
  matchId: number;
  gameweek: number;
  date: string;
  name: string;
  players: PlayerTrendMatchPlayer[];
}

export const hammarbyPlayerTrendMatches: PlayerTrendMatch[] = [
  {
    "matchId": 1682,
    "gameweek": 1,
    "date": "2026-04-04",
    "name": "Hammarby - Mjällby, 3-0",
    "players": [
      {
        "playerId": 4610,
        "playerName": "B. Hedlöf",
        "roleName": "Midfielder",
        "minutes": 0,
        "metrics": {
          "passes": 0,
          "passAccuracy": 0,
          "forwardPasses": 0,
          "forwardPassAccuracy": 0,
          "passesToFinalThird": 0,
          "finalThirdPassAccuracy": 0,
          "keyPasses": 0,
          "xA": 0,
          "shots": 0,
          "shotsOnTarget": 0,
          "xG": 0,
          "touchesInBox": 0,
          "dribbles": 0,
          "dribbleSuccess": 0,
          "defensiveDuels": 0,
          "defensiveDuelWinRate": 0,
          "aerialDuels": 0,
          "aerialDuelWinRate": 0,
          "recoveries": 0
        }
      },
      {
        "playerId": 3971,
        "playerName": "F. Adjei",
        "roleName": "Forward",
        "minutes": 15,
        "metrics": {
          "passes": 15,
          "passAccuracy": 93.33,
          "forwardPasses": 5,
          "forwardPassAccuracy": 80,
          "passesToFinalThird": 1,
          "finalThirdPassAccuracy": 0,
          "keyPasses": 0,
          "xA": 0,
          "shots": 0,
          "shotsOnTarget": 0,
          "xG": 0,
          "touchesInBox": 0,
          "dribbles": 0,
          "dribbleSuccess": 0,
          "defensiveDuels": 0,
          "defensiveDuelWinRate": 0,
          "aerialDuels": 0,
          "aerialDuelWinRate": 0,
          "recoveries": 4
        }
      },
      {
        "playerId": 3957,
        "playerName": "F. Jakobsson",
        "roleName": "Goalkeeper",
        "minutes": 0,
        "metrics": {
          "passes": 0,
          "passAccuracy": 0,
          "forwardPasses": 0,
          "forwardPassAccuracy": 0,
          "passesToFinalThird": 0,
          "finalThirdPassAccuracy": 0,
          "keyPasses": 0,
          "xA": 0,
          "shots": 0,
          "shotsOnTarget": 0,
          "xG": 0,
          "touchesInBox": 0,
          "dribbles": 0,
          "dribbleSuccess": 0,
          "defensiveDuels": 0,
          "defensiveDuelWinRate": 0,
          "aerialDuels": 0,
          "aerialDuelWinRate": 0,
          "recoveries": 0
        }
      },
      {
        "playerId": 3959,
        "playerName": "F. Winther",
        "roleName": "Defender",
        "minutes": 95,
        "metrics": {
          "passes": 56,
          "passAccuracy": 83.93,
          "forwardPasses": 19,
          "forwardPassAccuracy": 78.95,
          "passesToFinalThird": 6,
          "finalThirdPassAccuracy": 50,
          "keyPasses": 1,
          "xA": 0.01,
          "shots": 0,
          "shotsOnTarget": 0,
          "xG": 0,
          "touchesInBox": 1,
          "dribbles": 4,
          "dribbleSuccess": 100,
          "defensiveDuels": 17,
          "defensiveDuelWinRate": 11.76,
          "aerialDuels": 5,
          "aerialDuelWinRate": 60,
          "recoveries": 12
        }
      },
      {
        "playerId": 3976,
        "playerName": "H. Skoglund",
        "roleName": "Defender",
        "minutes": 95,
        "metrics": {
          "passes": 58,
          "passAccuracy": 81.03,
          "forwardPasses": 18,
          "forwardPassAccuracy": 72.22,
          "passesToFinalThird": 5,
          "finalThirdPassAccuracy": 40,
          "keyPasses": 1,
          "xA": 0.15,
          "shots": 1,
          "shotsOnTarget": 0,
          "xG": 0.07,
          "touchesInBox": 3,
          "dribbles": 2,
          "dribbleSuccess": 50,
          "defensiveDuels": 14,
          "defensiveDuelWinRate": 35.71,
          "aerialDuels": 2,
          "aerialDuelWinRate": 50,
          "recoveries": 10
        }
      },
      {
        "playerId": 3963,
        "playerName": "I. Fofana",
        "roleName": "Midfielder",
        "minutes": 95,
        "metrics": {
          "passes": 73,
          "passAccuracy": 95.89,
          "forwardPasses": 27,
          "forwardPassAccuracy": 92.59,
          "passesToFinalThird": 9,
          "finalThirdPassAccuracy": 88.89,
          "keyPasses": 0,
          "xA": 0,
          "shots": 0,
          "shotsOnTarget": 0,
          "xG": 0,
          "touchesInBox": 0,
          "dribbles": 1,
          "dribbleSuccess": 100,
          "defensiveDuels": 11,
          "defensiveDuelWinRate": 18.18,
          "aerialDuels": 2,
          "aerialDuelWinRate": 100,
          "recoveries": 10
        }
      },
      {
        "playerId": 3972,
        "playerName": "M. Kaboré",
        "roleName": "Forward",
        "minutes": 4,
        "metrics": {
          "passes": 1,
          "passAccuracy": 100,
          "forwardPasses": 0,
          "forwardPassAccuracy": 0,
          "passesToFinalThird": 0,
          "finalThirdPassAccuracy": 0,
          "keyPasses": 0,
          "xA": 0,
          "shots": 0,
          "shotsOnTarget": 0,
          "xG": 0,
          "touchesInBox": 0,
          "dribbles": 1,
          "dribbleSuccess": 100,
          "defensiveDuels": 0,
          "defensiveDuelWinRate": 0,
          "aerialDuels": 0,
          "aerialDuelWinRate": 0,
          "recoveries": 0
        }
      },
      {
        "playerId": 3970,
        "playerName": "M. Karlsson",
        "roleName": "Midfielder",
        "minutes": 95,
        "metrics": {
          "passes": 49,
          "passAccuracy": 91.84,
          "forwardPasses": 11,
          "forwardPassAccuracy": 72.73,
          "passesToFinalThird": 1,
          "finalThirdPassAccuracy": 100,
          "keyPasses": 0,
          "xA": 0.02,
          "shots": 0,
          "shotsOnTarget": 0,
          "xG": 0,
          "touchesInBox": 0,
          "dribbles": 5,
          "dribbleSuccess": 60,
          "defensiveDuels": 8,
          "defensiveDuelWinRate": 12.5,
          "aerialDuels": 2,
          "aerialDuelWinRate": 100,
          "recoveries": 18
        }
      },
      {
        "playerId": 3964,
        "playerName": "Montader Madjed",
        "roleName": "Forward",
        "minutes": 80,
        "metrics": {
          "passes": 35,
          "passAccuracy": 88.57,
          "forwardPasses": 5,
          "forwardPassAccuracy": 100,
          "passesToFinalThird": 1,
          "finalThirdPassAccuracy": 100,
          "keyPasses": 0,
          "xA": 0,
          "shots": 2,
          "shotsOnTarget": 0,
          "xG": 0.08,
          "touchesInBox": 1,
          "dribbles": 11,
          "dribbleSuccess": 54.55,
          "defensiveDuels": 0,
          "defensiveDuelWinRate": 0,
          "aerialDuels": 0,
          "aerialDuelWinRate": 0,
          "recoveries": 3
        }
      },
      {
        "playerId": 3953,
        "playerName": "N. Besara",
        "roleName": "Midfielder",
        "minutes": 92,
        "metrics": {
          "passes": 38,
          "passAccuracy": 84.21,
          "forwardPasses": 8,
          "forwardPassAccuracy": 75,
          "passesToFinalThird": 4,
          "finalThirdPassAccuracy": 50,
          "keyPasses": 2,
          "xA": 0.67,
          "shots": 4,
          "shotsOnTarget": 0,
          "xG": 0.06,
          "touchesInBox": 1,
          "dribbles": 2,
          "dribbleSuccess": 100,
          "defensiveDuels": 3,
          "defensiveDuelWinRate": 0,
          "aerialDuels": 1,
          "aerialDuelWinRate": 0,
          "recoveries": 1
        }
      },
      {
        "playerId": 3968,
        "playerName": "N. Persson",
        "roleName": "Defender",
        "minutes": 28,
        "metrics": {
          "passes": 7,
          "passAccuracy": 85.71,
          "forwardPasses": 1,
          "forwardPassAccuracy": 100,
          "passesToFinalThird": 0,
          "finalThirdPassAccuracy": 0,
          "keyPasses": 0,
          "xA": 0,
          "shots": 0,
          "shotsOnTarget": 0,
          "xG": 0,
          "touchesInBox": 0,
          "dribbles": 0,
          "dribbleSuccess": 0,
          "defensiveDuels": 1,
          "defensiveDuelWinRate": 0,
          "aerialDuels": 0,
          "aerialDuelWinRate": 0,
          "recoveries": 2
        }
      },
      {
        "playerId": 3958,
        "playerName": "N. Vasić",
        "roleName": "Forward",
        "minutes": 0,
        "metrics": {
          "passes": 0,
          "passAccuracy": 0,
          "forwardPasses": 0,
          "forwardPassAccuracy": 0,
          "passesToFinalThird": 0,
          "finalThirdPassAccuracy": 0,
          "keyPasses": 0,
          "xA": 0,
          "shots": 0,
          "shotsOnTarget": 0,
          "xG": 0,
          "touchesInBox": 0,
          "dribbles": 0,
          "dribbleSuccess": 0,
          "defensiveDuels": 0,
          "defensiveDuelWinRate": 0,
          "aerialDuels": 0,
          "aerialDuelWinRate": 0,
          "recoveries": 0
        }
      },
      {
        "playerId": 3955,
        "playerName": "O. Johansson",
        "roleName": "Midfielder",
        "minutes": 80,
        "metrics": {
          "passes": 43,
          "passAccuracy": 88.37,
          "forwardPasses": 13,
          "forwardPassAccuracy": 84.62,
          "passesToFinalThird": 8,
          "finalThirdPassAccuracy": 75,
          "keyPasses": 0,
          "xA": 0,
          "shots": 1,
          "shotsOnTarget": 0,
          "xG": 0.1,
          "touchesInBox": 0,
          "dribbles": 0,
          "dribbleSuccess": 0,
          "defensiveDuels": 10,
          "defensiveDuelWinRate": 20,
          "aerialDuels": 2,
          "aerialDuelWinRate": 100,
          "recoveries": 9
        }
      },
      {
        "playerId": 3969,
        "playerName": "O. Steinke Brånby",
        "roleName": "Midfielder",
        "minutes": 15,
        "metrics": {
          "passes": 3,
          "passAccuracy": 100,
          "forwardPasses": 1,
          "forwardPassAccuracy": 100,
          "passesToFinalThird": 0,
          "finalThirdPassAccuracy": 0,
          "keyPasses": 0,
          "xA": 0,
          "shots": 0,
          "shotsOnTarget": 0,
          "xG": 0,
          "touchesInBox": 0,
          "dribbles": 2,
          "dribbleSuccess": 50,
          "defensiveDuels": 1,
          "defensiveDuelWinRate": 0,
          "aerialDuels": 0,
          "aerialDuelWinRate": 0,
          "recoveries": 0
        }
      },
      {
        "playerId": 3966,
        "playerName": "P. Abraham",
        "roleName": "Forward",
        "minutes": 92,
        "metrics": {
          "passes": 25,
          "passAccuracy": 80,
          "forwardPasses": 6,
          "forwardPassAccuracy": 66.67,
          "passesToFinalThird": 0,
          "finalThirdPassAccuracy": 0,
          "keyPasses": 0,
          "xA": 0.01,
          "shots": 6,
          "shotsOnTarget": 4,
          "xG": 1.1,
          "touchesInBox": 7,
          "dribbles": 9,
          "dribbleSuccess": 77.78,
          "defensiveDuels": 12,
          "defensiveDuelWinRate": 16.67,
          "aerialDuels": 2,
          "aerialDuelWinRate": 0,
          "recoveries": 4
        }
      },
      {
        "playerId": 3977,
        "playerName": "S. Kone",
        "roleName": "Unknown",
        "minutes": 4,
        "metrics": {
          "passes": 2,
          "passAccuracy": 50,
          "forwardPasses": 0,
          "forwardPassAccuracy": 0,
          "passesToFinalThird": 0,
          "finalThirdPassAccuracy": 0,
          "keyPasses": 0,
          "xA": 0,
          "shots": 0,
          "shotsOnTarget": 0,
          "xG": 0,
          "touchesInBox": 0,
          "dribbles": 0,
          "dribbleSuccess": 0,
          "defensiveDuels": 2,
          "defensiveDuelWinRate": 0,
          "aerialDuels": 1,
          "aerialDuelWinRate": 0,
          "recoveries": 0
        }
      },
      {
        "playerId": 3961,
        "playerName": "V. Eriksson",
        "roleName": "Defender",
        "minutes": 95,
        "metrics": {
          "passes": 59,
          "passAccuracy": 100,
          "forwardPasses": 13,
          "forwardPassAccuracy": 100,
          "passesToFinalThird": 2,
          "finalThirdPassAccuracy": 100,
          "keyPasses": 0,
          "xA": 0,
          "shots": 1,
          "shotsOnTarget": 0,
          "xG": 0.22,
          "touchesInBox": 1,
          "dribbles": 0,
          "dribbleSuccess": 0,
          "defensiveDuels": 9,
          "defensiveDuelWinRate": 33.33,
          "aerialDuels": 10,
          "aerialDuelWinRate": 70,
          "recoveries": 15
        }
      },
      {
        "playerId": 3771,
        "playerName": "V. Lind",
        "roleName": "Forward",
        "minutes": 68,
        "metrics": {
          "passes": 27,
          "passAccuracy": 74.07,
          "forwardPasses": 10,
          "forwardPassAccuracy": 50,
          "passesToFinalThird": 5,
          "finalThirdPassAccuracy": 40,
          "keyPasses": 0,
          "xA": 0,
          "shots": 1,
          "shotsOnTarget": 1,
          "xG": 0.15,
          "touchesInBox": 2,
          "dribbles": 2,
          "dribbleSuccess": 100,
          "defensiveDuels": 9,
          "defensiveDuelWinRate": 22.22,
          "aerialDuels": 0,
          "aerialDuelWinRate": 0,
          "recoveries": 6
        }
      },
      {
        "playerId": 3954,
        "playerName": "W. Hahn",
        "roleName": "Goalkeeper",
        "minutes": 95,
        "metrics": {
          "passes": 30,
          "passAccuracy": 76.67,
          "forwardPasses": 23,
          "forwardPassAccuracy": 69.57,
          "passesToFinalThird": 3,
          "finalThirdPassAccuracy": 33.33,
          "keyPasses": 0,
          "xA": 0,
          "shots": 0,
          "shotsOnTarget": 0,
          "xG": 0,
          "touchesInBox": 0,
          "dribbles": 0,
          "dribbleSuccess": 0,
          "defensiveDuels": 0,
          "defensiveDuelWinRate": 0,
          "aerialDuels": 0,
          "aerialDuelWinRate": 0,
          "recoveries": 5
        }
      },
      {
        "playerId": 3979,
        "playerName": "W. Lindberg Uhrstrom",
        "roleName": "Unknown",
        "minutes": 0,
        "metrics": {
          "passes": 0,
          "passAccuracy": 0,
          "forwardPasses": 0,
          "forwardPassAccuracy": 0,
          "passesToFinalThird": 0,
          "finalThirdPassAccuracy": 0,
          "keyPasses": 0,
          "xA": 0,
          "shots": 0,
          "shotsOnTarget": 0,
          "xG": 0,
          "touchesInBox": 0,
          "dribbles": 0,
          "dribbleSuccess": 0,
          "defensiveDuels": 0,
          "defensiveDuelWinRate": 0,
          "aerialDuels": 0,
          "aerialDuelWinRate": 0,
          "recoveries": 0
        }
      }
    ]
  },
  {
    "matchId": 1696,
    "gameweek": 2,
    "date": "2026-04-13",
    "name": "Sirius - Hammarby, 2-0",
    "players": [
      {
        "playerId": 4610,
        "playerName": "B. Hedlöf",
        "roleName": "Midfielder",
        "minutes": 0,
        "metrics": {
          "passes": 0,
          "passAccuracy": 0,
          "forwardPasses": 0,
          "forwardPassAccuracy": 0,
          "passesToFinalThird": 0,
          "finalThirdPassAccuracy": 0,
          "keyPasses": 0,
          "xA": 0,
          "shots": 0,
          "shotsOnTarget": 0,
          "xG": 0,
          "touchesInBox": 0,
          "dribbles": 0,
          "dribbleSuccess": 0,
          "defensiveDuels": 0,
          "defensiveDuelWinRate": 0,
          "aerialDuels": 0,
          "aerialDuelWinRate": 0,
          "recoveries": 0
        }
      },
      {
        "playerId": 3971,
        "playerName": "F. Adjei",
        "roleName": "Forward",
        "minutes": 12,
        "metrics": {
          "passes": 7,
          "passAccuracy": 85.71,
          "forwardPasses": 4,
          "forwardPassAccuracy": 75,
          "passesToFinalThird": 1,
          "finalThirdPassAccuracy": 100,
          "keyPasses": 0,
          "xA": 0,
          "shots": 0,
          "shotsOnTarget": 0,
          "xG": 0,
          "touchesInBox": 0,
          "dribbles": 1,
          "dribbleSuccess": 100,
          "defensiveDuels": 0,
          "defensiveDuelWinRate": 0,
          "aerialDuels": 0,
          "aerialDuelWinRate": 0,
          "recoveries": 2
        }
      },
      {
        "playerId": 3957,
        "playerName": "F. Jakobsson",
        "roleName": "Goalkeeper",
        "minutes": 0,
        "metrics": {
          "passes": 0,
          "passAccuracy": 0,
          "forwardPasses": 0,
          "forwardPassAccuracy": 0,
          "passesToFinalThird": 0,
          "finalThirdPassAccuracy": 0,
          "keyPasses": 0,
          "xA": 0,
          "shots": 0,
          "shotsOnTarget": 0,
          "xG": 0,
          "touchesInBox": 0,
          "dribbles": 0,
          "dribbleSuccess": 0,
          "defensiveDuels": 0,
          "defensiveDuelWinRate": 0,
          "aerialDuels": 0,
          "aerialDuelWinRate": 0,
          "recoveries": 0
        }
      },
      {
        "playerId": 3959,
        "playerName": "F. Winther",
        "roleName": "Defender",
        "minutes": 96,
        "metrics": {
          "passes": 93,
          "passAccuracy": 90.32,
          "forwardPasses": 28,
          "forwardPassAccuracy": 82.14,
          "passesToFinalThird": 12,
          "finalThirdPassAccuracy": 83.33,
          "keyPasses": 0,
          "xA": 0.08,
          "shots": 3,
          "shotsOnTarget": 0,
          "xG": 0.05,
          "touchesInBox": 0,
          "dribbles": 2,
          "dribbleSuccess": 100,
          "defensiveDuels": 6,
          "defensiveDuelWinRate": 33.33,
          "aerialDuels": 6,
          "aerialDuelWinRate": 83.33,
          "recoveries": 11
        }
      },
      {
        "playerId": 3976,
        "playerName": "H. Skoglund",
        "roleName": "Defender",
        "minutes": 96,
        "metrics": {
          "passes": 65,
          "passAccuracy": 87.69,
          "forwardPasses": 18,
          "forwardPassAccuracy": 77.78,
          "passesToFinalThird": 7,
          "finalThirdPassAccuracy": 100,
          "keyPasses": 1,
          "xA": 0,
          "shots": 1,
          "shotsOnTarget": 0,
          "xG": 0.44,
          "touchesInBox": 4,
          "dribbles": 0,
          "dribbleSuccess": 0,
          "defensiveDuels": 11,
          "defensiveDuelWinRate": 18.18,
          "aerialDuels": 1,
          "aerialDuelWinRate": 0,
          "recoveries": 13
        }
      },
      {
        "playerId": 3963,
        "playerName": "I. Fofana",
        "roleName": "Midfielder",
        "minutes": 64,
        "metrics": {
          "passes": 75,
          "passAccuracy": 92,
          "forwardPasses": 25,
          "forwardPassAccuracy": 84,
          "passesToFinalThird": 10,
          "finalThirdPassAccuracy": 80,
          "keyPasses": 0,
          "xA": 0,
          "shots": 1,
          "shotsOnTarget": 0,
          "xG": 0.02,
          "touchesInBox": 1,
          "dribbles": 0,
          "dribbleSuccess": 0,
          "defensiveDuels": 2,
          "defensiveDuelWinRate": 50,
          "aerialDuels": 1,
          "aerialDuelWinRate": 100,
          "recoveries": 6
        }
      },
      {
        "playerId": 3972,
        "playerName": "M. Kaboré",
        "roleName": "Forward",
        "minutes": 64,
        "metrics": {
          "passes": 14,
          "passAccuracy": 78.57,
          "forwardPasses": 0,
          "forwardPassAccuracy": 0,
          "passesToFinalThird": 0,
          "finalThirdPassAccuracy": 0,
          "keyPasses": 0,
          "xA": 0,
          "shots": 0,
          "shotsOnTarget": 0,
          "xG": 0,
          "touchesInBox": 3,
          "dribbles": 0,
          "dribbleSuccess": 0,
          "defensiveDuels": 2,
          "defensiveDuelWinRate": 0,
          "aerialDuels": 2,
          "aerialDuelWinRate": 50,
          "recoveries": 0
        }
      },
      {
        "playerId": 3970,
        "playerName": "M. Karlsson",
        "roleName": "Midfielder",
        "minutes": 96,
        "metrics": {
          "passes": 87,
          "passAccuracy": 87.36,
          "forwardPasses": 16,
          "forwardPassAccuracy": 62.5,
          "passesToFinalThird": 6,
          "finalThirdPassAccuracy": 66.67,
          "keyPasses": 0,
          "xA": 0.05,
          "shots": 0,
          "shotsOnTarget": 0,
          "xG": 0,
          "touchesInBox": 1,
          "dribbles": 2,
          "dribbleSuccess": 100,
          "defensiveDuels": 7,
          "defensiveDuelWinRate": 14.29,
          "aerialDuels": 2,
          "aerialDuelWinRate": 50,
          "recoveries": 8
        }
      },
      {
        "playerId": 3964,
        "playerName": "Montader Madjed",
        "roleName": "Forward",
        "minutes": 84,
        "metrics": {
          "passes": 51,
          "passAccuracy": 82.35,
          "forwardPasses": 9,
          "forwardPassAccuracy": 77.78,
          "passesToFinalThird": 7,
          "finalThirdPassAccuracy": 71.43,
          "keyPasses": 0,
          "xA": 0.23,
          "shots": 2,
          "shotsOnTarget": 1,
          "xG": 0.07,
          "touchesInBox": 2,
          "dribbles": 8,
          "dribbleSuccess": 75,
          "defensiveDuels": 0,
          "defensiveDuelWinRate": 0,
          "aerialDuels": 1,
          "aerialDuelWinRate": 0,
          "recoveries": 3
        }
      },
      {
        "playerId": 3953,
        "playerName": "N. Besara",
        "roleName": "Midfielder",
        "minutes": 96,
        "metrics": {
          "passes": 40,
          "passAccuracy": 97.5,
          "forwardPasses": 5,
          "forwardPassAccuracy": 80,
          "passesToFinalThird": 8,
          "finalThirdPassAccuracy": 87.5,
          "keyPasses": 0,
          "xA": 0,
          "shots": 3,
          "shotsOnTarget": 0,
          "xG": 0.16,
          "touchesInBox": 4,
          "dribbles": 1,
          "dribbleSuccess": 100,
          "defensiveDuels": 0,
          "defensiveDuelWinRate": 0,
          "aerialDuels": 1,
          "aerialDuelWinRate": 0,
          "recoveries": 1
        }
      },
      {
        "playerId": 3968,
        "playerName": "N. Persson",
        "roleName": "Defender",
        "minutes": 18,
        "metrics": {
          "passes": 10,
          "passAccuracy": 60,
          "forwardPasses": 3,
          "forwardPassAccuracy": 0,
          "passesToFinalThird": 1,
          "finalThirdPassAccuracy": 0,
          "keyPasses": 0,
          "xA": 0.04,
          "shots": 0,
          "shotsOnTarget": 0,
          "xG": 0,
          "touchesInBox": 0,
          "dribbles": 1,
          "dribbleSuccess": 100,
          "defensiveDuels": 1,
          "defensiveDuelWinRate": 0,
          "aerialDuels": 2,
          "aerialDuelWinRate": 50,
          "recoveries": 2
        }
      },
      {
        "playerId": 4593,
        "playerName": "O. Hagen",
        "roleName": "Midfielder",
        "minutes": 18,
        "metrics": {
          "passes": 17,
          "passAccuracy": 76.47,
          "forwardPasses": 2,
          "forwardPassAccuracy": 100,
          "passesToFinalThird": 1,
          "finalThirdPassAccuracy": 100,
          "keyPasses": 1,
          "xA": 0.32,
          "shots": 1,
          "shotsOnTarget": 0,
          "xG": 0.04,
          "touchesInBox": 2,
          "dribbles": 3,
          "dribbleSuccess": 100,
          "defensiveDuels": 0,
          "defensiveDuelWinRate": 0,
          "aerialDuels": 1,
          "aerialDuelWinRate": 100,
          "recoveries": 0
        }
      },
      {
        "playerId": 3955,
        "playerName": "O. Johansson",
        "roleName": "Midfielder",
        "minutes": 78,
        "metrics": {
          "passes": 67,
          "passAccuracy": 86.57,
          "forwardPasses": 21,
          "forwardPassAccuracy": 76.19,
          "passesToFinalThird": 8,
          "finalThirdPassAccuracy": 100,
          "keyPasses": 0,
          "xA": 0.14,
          "shots": 1,
          "shotsOnTarget": 0,
          "xG": 0.2,
          "touchesInBox": 2,
          "dribbles": 1,
          "dribbleSuccess": 100,
          "defensiveDuels": 7,
          "defensiveDuelWinRate": 28.57,
          "aerialDuels": 1,
          "aerialDuelWinRate": 0,
          "recoveries": 9
        }
      },
      {
        "playerId": 3969,
        "playerName": "O. Steinke Brånby",
        "roleName": "Midfielder",
        "minutes": 0,
        "metrics": {
          "passes": 0,
          "passAccuracy": 0,
          "forwardPasses": 0,
          "forwardPassAccuracy": 0,
          "passesToFinalThird": 0,
          "finalThirdPassAccuracy": 0,
          "keyPasses": 0,
          "xA": 0,
          "shots": 0,
          "shotsOnTarget": 0,
          "xG": 0,
          "touchesInBox": 0,
          "dribbles": 0,
          "dribbleSuccess": 0,
          "defensiveDuels": 0,
          "defensiveDuelWinRate": 0,
          "aerialDuels": 0,
          "aerialDuelWinRate": 0,
          "recoveries": 0
        }
      },
      {
        "playerId": 3966,
        "playerName": "P. Abraham",
        "roleName": "Forward",
        "minutes": 31,
        "metrics": {
          "passes": 10,
          "passAccuracy": 80,
          "forwardPasses": 1,
          "forwardPassAccuracy": 100,
          "passesToFinalThird": 1,
          "finalThirdPassAccuracy": 100,
          "keyPasses": 0,
          "xA": 0,
          "shots": 1,
          "shotsOnTarget": 0,
          "xG": 0.32,
          "touchesInBox": 1,
          "dribbles": 0,
          "dribbleSuccess": 0,
          "defensiveDuels": 0,
          "defensiveDuelWinRate": 0,
          "aerialDuels": 1,
          "aerialDuelWinRate": 100,
          "recoveries": 0
        }
      },
      {
        "playerId": 3977,
        "playerName": "S. Kone",
        "roleName": "Unknown",
        "minutes": 0,
        "metrics": {
          "passes": 0,
          "passAccuracy": 0,
          "forwardPasses": 0,
          "forwardPassAccuracy": 0,
          "passesToFinalThird": 0,
          "finalThirdPassAccuracy": 0,
          "keyPasses": 0,
          "xA": 0,
          "shots": 0,
          "shotsOnTarget": 0,
          "xG": 0,
          "touchesInBox": 0,
          "dribbles": 0,
          "dribbleSuccess": 0,
          "defensiveDuels": 0,
          "defensiveDuelWinRate": 0,
          "aerialDuels": 0,
          "aerialDuelWinRate": 0,
          "recoveries": 0
        }
      },
      {
        "playerId": 3956,
        "playerName": "T. Tekie",
        "roleName": "Midfielder",
        "minutes": 31,
        "metrics": {
          "passes": 36,
          "passAccuracy": 88.89,
          "forwardPasses": 11,
          "forwardPassAccuracy": 63.64,
          "passesToFinalThird": 6,
          "finalThirdPassAccuracy": 66.67,
          "keyPasses": 0,
          "xA": 0,
          "shots": 1,
          "shotsOnTarget": 1,
          "xG": 0.02,
          "touchesInBox": 0,
          "dribbles": 0,
          "dribbleSuccess": 0,
          "defensiveDuels": 1,
          "defensiveDuelWinRate": 0,
          "aerialDuels": 0,
          "aerialDuelWinRate": 0,
          "recoveries": 2
        }
      },
      {
        "playerId": 3961,
        "playerName": "V. Eriksson",
        "roleName": "Defender",
        "minutes": 96,
        "metrics": {
          "passes": 74,
          "passAccuracy": 95.95,
          "forwardPasses": 22,
          "forwardPassAccuracy": 90.91,
          "passesToFinalThird": 1,
          "finalThirdPassAccuracy": 100,
          "keyPasses": 0,
          "xA": 0,
          "shots": 0,
          "shotsOnTarget": 0,
          "xG": 0,
          "touchesInBox": 0,
          "dribbles": 0,
          "dribbleSuccess": 0,
          "defensiveDuels": 16,
          "defensiveDuelWinRate": 56.25,
          "aerialDuels": 8,
          "aerialDuelWinRate": 75,
          "recoveries": 30
        }
      },
      {
        "playerId": 3771,
        "playerName": "V. Lind",
        "roleName": "Forward",
        "minutes": 78,
        "metrics": {
          "passes": 26,
          "passAccuracy": 80.77,
          "forwardPasses": 4,
          "forwardPassAccuracy": 75,
          "passesToFinalThird": 2,
          "finalThirdPassAccuracy": 100,
          "keyPasses": 0,
          "xA": 0,
          "shots": 2,
          "shotsOnTarget": 1,
          "xG": 0.09,
          "touchesInBox": 2,
          "dribbles": 3,
          "dribbleSuccess": 66.67,
          "defensiveDuels": 4,
          "defensiveDuelWinRate": 0,
          "aerialDuels": 1,
          "aerialDuelWinRate": 100,
          "recoveries": 2
        }
      },
      {
        "playerId": 3954,
        "playerName": "W. Hahn",
        "roleName": "Goalkeeper",
        "minutes": 96,
        "metrics": {
          "passes": 17,
          "passAccuracy": 88.24,
          "forwardPasses": 7,
          "forwardPassAccuracy": 71.43,
          "passesToFinalThird": 1,
          "finalThirdPassAccuracy": 100,
          "keyPasses": 0,
          "xA": 0,
          "shots": 0,
          "shotsOnTarget": 0,
          "xG": 0,
          "touchesInBox": 0,
          "dribbles": 0,
          "dribbleSuccess": 0,
          "defensiveDuels": 0,
          "defensiveDuelWinRate": 0,
          "aerialDuels": 0,
          "aerialDuelWinRate": 0,
          "recoveries": 2
        }
      }
    ]
  }
];
