export type SquadAgeBandKey = "u18" | "u19u21" | "u22u23" | "peak" | "twilight";

export type SquadPlayerRole = "Goalkeeper" | "Defender" | "Midfielder" | "Forward";

export type HammarbySquadPlayer = {
  playerId: number;
  name: string;
  firstName: string;
  lastName: string;
  birthDate: string;
  birthYear: number;
  age: number;
  ageBand: SquadAgeBandKey;
  roleName: SquadPlayerRole;
  roleCode: string;
  minutes: number;
  matches: number;
  starts: number;
  subbedIn: number;
  goals: number;
  assists: number;
  contractExpiration: string | null;
};

export type SquadAgeBandDefinition = {
  key: SquadAgeBandKey;
  label: string;
  shortLabel: string;
  description: string;
  color: string;
};

export type HammarbySquadAgeStructureSeason = {
  season: 2026;
  label: string;
  status: string;
  teamName: string;
  sourceUrl: string;
  sourceApiUrl: string;
  players: HammarbySquadPlayer[];
};

export const squadAgeBandDefinitions: SquadAgeBandDefinition[] = [
  {
    key: "u18",
    label: "U18",
    shortLabel: "U18",
    description: "Akademi- och juniorålder.",
    color: "#7dd3fc",
  },
  {
    key: "u19u21",
    label: "U19-U21",
    shortLabel: "19-21",
    description: "Talangåren där spelare börjar närma sig seniorrotation.",
    color: "#22c55e",
  },
  {
    key: "u22u23",
    label: "U22-U23",
    shortLabel: "22-23",
    description: "Sista utvecklingssteget innan peak-åren.",
    color: "#facc15",
  },
  {
    key: "peak",
    label: "Peak 24-29",
    shortLabel: "Peak",
    description: "Senioråren där truppen oftast bör bära mest minuter.",
    color: "#fb923c",
  },
  {
    key: "twilight",
    label: "Twilight 30+",
    shortLabel: "30+",
    description: "Rutinerade spelare och veteranminuter.",
    color: "#64748b",
  },
];

export const hammarbySquadAgeStructure2026: HammarbySquadAgeStructureSeason = {
  season: 2026,
  label: "2026",
  status: "Pågående säsong",
  teamName: "Hammarby IF",
  sourceUrl: "https://bolldata.se/trupper?season_name=2026",
  sourceApiUrl: "https://bolldata.se/api/team-advanced/?season_name=2026",
  players: [
    {
      playerId: 9926,
      name: "W. Hahn",
      firstName: "Warner",
      lastName: "Hahn",
      birthDate: "1992-06-15",
      birthYear: 1992,
      age: 34,
      ageBand: "twilight",
      roleName: "Goalkeeper",
      roleCode: "GK",
      minutes: 1067,
      matches: 11,
      starts: 11,
      subbedIn: 0,
      goals: 0,
      assists: 0,
      contractExpiration: "2027-12-31",
    },
    {
      playerId: 9941,
      name: "M. Karlsson",
      firstName: "Markus",
      lastName: "Karlsson",
      birthDate: "2004-01-20",
      birthYear: 2004,
      age: 22,
      ageBand: "u22u23",
      roleName: "Midfielder",
      roleCode: "MD",
      minutes: 1060,
      matches: 11,
      starts: 11,
      subbedIn: 0,
      goals: 0,
      assists: 1,
      contractExpiration: "2029-12-31",
    },
    {
      playerId: 9932,
      name: "V. Eriksson",
      firstName: "Victor",
      lastName: "Eriksson",
      birthDate: "2000-09-17",
      birthYear: 2000,
      age: 26,
      ageBand: "peak",
      roleName: "Defender",
      roleCode: "DF",
      minutes: 1053,
      matches: 11,
      starts: 11,
      subbedIn: 0,
      goals: 1,
      assists: 0,
      contractExpiration: "2028-12-31",
    },
    {
      playerId: 9931,
      name: "F. Winther",
      firstName: "Frederik",
      lastName: "Winther",
      birthDate: "2001-01-04",
      birthYear: 2001,
      age: 25,
      ageBand: "peak",
      roleName: "Defender",
      roleCode: "DF",
      minutes: 1043,
      matches: 11,
      starts: 11,
      subbedIn: 0,
      goals: 0,
      assists: 1,
      contractExpiration: "2027-12-31",
    },
    {
      playerId: 9944,
      name: "H. Skoglund",
      firstName: "Hampus",
      lastName: "Skoglund",
      birthDate: "2004-03-01",
      birthYear: 2004,
      age: 22,
      ageBand: "u22u23",
      roleName: "Defender",
      roleCode: "DF",
      minutes: 932,
      matches: 10,
      starts: 10,
      subbedIn: 0,
      goals: 0,
      assists: 2,
      contractExpiration: "2029-12-31",
    },
    {
      playerId: 9925,
      name: "N. Besara",
      firstName: "Nahir",
      lastName: "Besara",
      birthDate: "1991-02-25",
      birthYear: 1991,
      age: 35,
      ageBand: "twilight",
      roleName: "Midfielder",
      roleCode: "MD",
      minutes: 909,
      matches: 11,
      starts: 10,
      subbedIn: 1,
      goals: 5,
      assists: 5,
      contractExpiration: "2027-12-31",
    },
    {
      playerId: 9937,
      name: "P. Abraham",
      firstName: "Paulos",
      lastName: "Abraham",
      birthDate: "2002-07-16",
      birthYear: 2002,
      age: 24,
      ageBand: "peak",
      roleName: "Forward",
      roleCode: "FW",
      minutes: 869,
      matches: 11,
      starts: 10,
      subbedIn: 1,
      goals: 5,
      assists: 2,
      contractExpiration: "2028-12-31",
    },
    {
      playerId: 9936,
      name: "Montader Madjed",
      firstName: "Montader",
      lastName: "Madjed",
      birthDate: "2005-04-24",
      birthYear: 2005,
      age: 21,
      ageBand: "u19u21",
      roleName: "Forward",
      roleCode: "FW",
      minutes: 837,
      matches: 11,
      starts: 10,
      subbedIn: 1,
      goals: 2,
      assists: 0,
      contractExpiration: "2028-12-31",
    },
    {
      playerId: 9933,
      name: "V. Lind",
      firstName: "Victor",
      lastName: "Stange Lind",
      birthDate: "2003-06-12",
      birthYear: 2003,
      age: 23,
      ageBand: "u22u23",
      roleName: "Forward",
      roleCode: "FW",
      minutes: 785,
      matches: 11,
      starts: 9,
      subbedIn: 2,
      goals: 5,
      assists: 2,
      contractExpiration: "2029-12-31",
    },
    {
      playerId: 9927,
      name: "O. Johansson",
      firstName: "Oscar Nils Per",
      lastName: "Johansson Schellhas",
      birthDate: "1995-05-06",
      birthYear: 1995,
      age: 31,
      ageBand: "twilight",
      roleName: "Midfielder",
      roleCode: "MD",
      minutes: 644,
      matches: 10,
      starts: 7,
      subbedIn: 3,
      goals: 0,
      assists: 2,
      contractExpiration: "2026-12-31",
    },
    {
      playerId: 9938,
      name: "N. Persson",
      firstName: "Noah",
      lastName: "Persson",
      birthDate: "2003-07-16",
      birthYear: 2003,
      age: 23,
      ageBand: "u22u23",
      roleName: "Defender",
      roleCode: "DF",
      minutes: 614,
      matches: 11,
      starts: 6,
      subbedIn: 5,
      goals: 1,
      assists: 1,
      contractExpiration: "2029-12-31",
    },
    {
      playerId: 9935,
      name: "I. Fofana",
      firstName: "Ibrahima",
      lastName: "Breze Fofana",
      birthDate: "2002-08-15",
      birthYear: 2002,
      age: 24,
      ageBand: "peak",
      roleName: "Midfielder",
      roleCode: "MD",
      minutes: 594,
      matches: 8,
      starts: 6,
      subbedIn: 2,
      goals: 1,
      assists: 0,
      contractExpiration: "2029-12-31",
    },
    {
      playerId: 9942,
      name: "F. Adjei",
      firstName: "Frank Junior",
      lastName: "Adjei",
      birthDate: "2004-03-20",
      birthYear: 2004,
      age: 22,
      ageBand: "u22u23",
      roleName: "Forward",
      roleCode: "FW",
      minutes: 372,
      matches: 9,
      starts: 3,
      subbedIn: 6,
      goals: 1,
      assists: 2,
      contractExpiration: "2029-12-31",
    },
    {
      playerId: 9928,
      name: "T. Tekie",
      firstName: "Tesfaldet",
      lastName: "Tekie",
      birthDate: "1997-06-04",
      birthYear: 1997,
      age: 29,
      ageBand: "peak",
      roleName: "Midfielder",
      roleCode: "MD",
      minutes: 280,
      matches: 5,
      starts: 3,
      subbedIn: 2,
      goals: 0,
      assists: 0,
      contractExpiration: "2026-12-31",
    },
    {
      playerId: 9939,
      name: "O. Hagen",
      firstName: "Oliver Jordan",
      lastName: "Hagen",
      birthDate: "2006-06-09",
      birthYear: 2006,
      age: 20,
      ageBand: "u19u21",
      roleName: "Midfielder",
      roleCode: "MD",
      minutes: 211,
      matches: 9,
      starts: 1,
      subbedIn: 8,
      goals: 0,
      assists: 0,
      contractExpiration: null,
    },
    {
      playerId: 9943,
      name: "M. Kaboré",
      firstName: "Moise Elohim",
      lastName: "Kaboré",
      birthDate: "2006-12-20",
      birthYear: 2006,
      age: 20,
      ageBand: "u19u21",
      roleName: "Forward",
      roleCode: "FW",
      minutes: 181,
      matches: 5,
      starts: 2,
      subbedIn: 3,
      goals: 0,
      assists: 0,
      contractExpiration: "2029-12-31",
    },
    {
      playerId: 9930,
      name: "N. Vasić",
      firstName: "Nikola",
      lastName: "Vasić",
      birthDate: "1991-10-04",
      birthYear: 1991,
      age: 35,
      ageBand: "twilight",
      roleName: "Forward",
      roleCode: "FW",
      minutes: 138,
      matches: 7,
      starts: 0,
      subbedIn: 7,
      goals: 3,
      assists: 0,
      contractExpiration: "2026-12-31",
    },
    {
      playerId: 9940,
      name: "O. Steinke Brånby",
      firstName: "Oscar",
      lastName: "Steinke Brånby",
      birthDate: "2006-02-07",
      birthYear: 2006,
      age: 20,
      ageBand: "u19u21",
      roleName: "Midfielder",
      roleCode: "MD",
      minutes: 77,
      matches: 5,
      starts: 0,
      subbedIn: 5,
      goals: 0,
      assists: 0,
      contractExpiration: "2030-12-31",
    },
    {
      playerId: 9946,
      name: "W. Lindberg Uhrström",
      firstName: "Wilson Elliot",
      lastName: "Lindberg Uhrström",
      birthDate: "2006-03-23",
      birthYear: 2006,
      age: 20,
      ageBand: "u19u21",
      roleName: "Midfielder",
      roleCode: "MD",
      minutes: 35,
      matches: 3,
      starts: 0,
      subbedIn: 3,
      goals: 0,
      assists: 1,
      contractExpiration: "2028-12-31",
    },
    {
      playerId: 9934,
      name: "D. Collander",
      firstName: "Dennis",
      lastName: "Collander",
      birthDate: "2002-05-09",
      birthYear: 2002,
      age: 24,
      ageBand: "peak",
      roleName: "Midfielder",
      roleCode: "MD",
      minutes: 12,
      matches: 2,
      starts: 0,
      subbedIn: 2,
      goals: 0,
      assists: 0,
      contractExpiration: "2026-07-14",
    },
    {
      playerId: 9945,
      name: "S. Kone",
      firstName: "Sourou",
      lastName: "Kone",
      birthDate: "2008-01-01",
      birthYear: 2008,
      age: 18,
      ageBand: "u18",
      roleName: "Midfielder",
      roleCode: "MD",
      minutes: 4,
      matches: 1,
      starts: 0,
      subbedIn: 1,
      goals: 0,
      assists: 0,
      contractExpiration: null,
    },
    {
      playerId: 9929,
      name: "F. Jakobsson",
      firstName: "Felix",
      lastName: "Jakobsson",
      birthDate: "1999-09-16",
      birthYear: 1999,
      age: 27,
      ageBand: "peak",
      roleName: "Goalkeeper",
      roleCode: "GK",
      minutes: 0,
      matches: 0,
      starts: 0,
      subbedIn: 0,
      goals: 0,
      assists: 0,
      contractExpiration: "2028-12-31",
    },
    {
      playerId: 9947,
      name: "E. Lwampindy Bofua",
      firstName: "Essayas",
      lastName: "Lwampindy Bofua",
      birthDate: "2005-08-10",
      birthYear: 2005,
      age: 21,
      ageBand: "u19u21",
      roleName: "Defender",
      roleCode: "DF",
      minutes: 0,
      matches: 0,
      starts: 0,
      subbedIn: 0,
      goals: 0,
      assists: 0,
      contractExpiration: "2029-12-31",
    },
    {
      playerId: 10008,
      name: "B. Hedlöf",
      firstName: "Björn",
      lastName: "Hedlöf",
      birthDate: "2008-07-14",
      birthYear: 2008,
      age: 18,
      ageBand: "u18",
      roleName: "Midfielder",
      roleCode: "MD",
      minutes: 0,
      matches: 0,
      starts: 0,
      subbedIn: 0,
      goals: 0,
      assists: 0,
      contractExpiration: "2027-12-31",
    },
    {
      playerId: 10020,
      name: "E. Fischerström",
      firstName: "Elton",
      lastName: "Fischerström Opančar",
      birthDate: "2007-01-02",
      birthYear: 2007,
      age: 19,
      ageBand: "u19u21",
      roleName: "Goalkeeper",
      roleCode: "GK",
      minutes: 0,
      matches: 0,
      starts: 0,
      subbedIn: 0,
      goals: 0,
      assists: 0,
      contractExpiration: "2029-12-31",
    },
  ],
};
