export type SquadAgeBandKey = "u18" | "u19u21" | "u22u23" | "peak" | "twilight";

export type SquadPlayerRole = "Goalkeeper" | "Defender" | "Midfielder" | "Forward";

export type HammarbySquadPlayer = {
  playerId: number;
  name: string;
  firstName: string;
  lastName: string;
  birthDate: string;
  birthYear: number;
  age: number;
  ageBand: SquadAgeBandKey;
  roleName: SquadPlayerRole;
  roleCode: string;
  minutes: number;
  matches: number;
  starts: number;
  subbedIn: number;
  goals: number;
  assists: number;
  contractExpiration: string | null;
};

export type SquadAgeBandDefinition = {
  key: SquadAgeBandKey;
  label: string;
  shortLabel: string;
  description: string;
  color: string;
};

export type HammarbySquadAgeStructureSeason = {
  season: 2024 | 2025 | 2026;
  label: string;
  status: string;
  teamName: string;
  sourceUrl: string;
  sourceApiUrl: string;
  players: HammarbySquadPlayer[];
};

export const squadAgeBandDefinitions: SquadAgeBandDefinition[] = [
  {
    key: "u18",
    label: "U18",
    shortLabel: "U18",
    description: "Akademi- och juniorålder.",
    color: "#7dd3fc",
  },
  {
    key: "u19u21",
    label: "U19-U21",
    shortLabel: "19-21",
    description: "Talangåren där spelare börjar närma sig seniorrotation.",
    color: "#22c55e",
  },
  {
    key: "u22u23",
    label: "U22-U23",
    shortLabel: "22-23",
    description: "Sista utvecklingssteget innan peak-åren.",
    color: "#facc15",
  },
  {
    key: "peak",
    label: "Peak 24-29",
    shortLabel: "Peak",
    description: "Senioråren där truppen oftast bör bära mest minuter.",
    color: "#fb923c",
  },
  {
    key: "twilight",
    label: "Twilight 30+",
    shortLabel: "30+",
    description: "Rutinerade spelare och veteranminuter.",
    color: "#64748b",
  },
];

export const hammarbySquadAgeStructureSeasons: HammarbySquadAgeStructureSeason[] = [
  {
    "season": 2024,
    "label": "2024",
    "status": "Hel säsong",
    "teamName": "Hammarby IF",
    "sourceUrl": "https://bolldata.se/trupper?season_name=2024",
    "sourceApiUrl": "https://bolldata.se/api/team-advanced/?season_name=2024",
    "players": [
      {
        "playerId": 6192,
        "name": "S. Pinas",
        "firstName": "Shaquille",
        "lastName": "Pinas",
        "birthDate": "1998-03-19",
        "birthYear": 1998,
        "age": 26,
        "ageBand": "peak",
        "roleName": "Defender",
        "roleCode": "DF",
        "minutes": 2668,
        "matches": 28,
        "starts": 28,
        "subbedIn": 0,
        "goals": 4,
        "assists": 3,
        "contractExpiration": "2028-06-30"
      },
      {
        "playerId": 6189,
        "name": "N. Besara",
        "firstName": "Nahir",
        "lastName": "Besara",
        "birthDate": "1991-02-25",
        "birthYear": 1991,
        "age": 33,
        "ageBand": "twilight",
        "roleName": "Midfielder",
        "roleCode": "MD",
        "minutes": 2655,
        "matches": 28,
        "starts": 28,
        "subbedIn": 0,
        "goals": 10,
        "assists": 6,
        "contractExpiration": "2027-12-31"
      },
      {
        "playerId": 6185,
        "name": "T. Tekie",
        "firstName": "Tesfaldet",
        "lastName": "Tekie",
        "birthDate": "1997-06-04",
        "birthYear": 1997,
        "age": 27,
        "ageBand": "peak",
        "roleName": "Midfielder",
        "roleCode": "MD",
        "minutes": 2432,
        "matches": 29,
        "starts": 25,
        "subbedIn": 4,
        "goals": 4,
        "assists": 2,
        "contractExpiration": "2026-12-31"
      },
      {
        "playerId": 6191,
        "name": "O. Johansson",
        "firstName": "Oscar Nils Per",
        "lastName": "Johansson Schellhas",
        "birthDate": "1995-05-06",
        "birthYear": 1995,
        "age": 29,
        "ageBand": "peak",
        "roleName": "Midfielder",
        "roleCode": "MD",
        "minutes": 2417,
        "matches": 29,
        "starts": 25,
        "subbedIn": 4,
        "goals": 4,
        "assists": 2,
        "contractExpiration": "2026-12-31"
      },
      {
        "playerId": 6184,
        "name": "H. Skoglund",
        "firstName": "Hampus",
        "lastName": "Skoglund",
        "birthDate": "2004-03-01",
        "birthYear": 2004,
        "age": 20,
        "ageBand": "u19u21",
        "roleName": "Defender",
        "roleCode": "DF",
        "minutes": 2283,
        "matches": 29,
        "starts": 25,
        "subbedIn": 4,
        "goals": 0,
        "assists": 1,
        "contractExpiration": "2029-12-31"
      },
      {
        "playerId": 6497,
        "name": "P. Vagić",
        "firstName": "Pavle",
        "lastName": "Vagić",
        "birthDate": "2000-01-24",
        "birthYear": 2000,
        "age": 24,
        "ageBand": "peak",
        "roleName": "Defender",
        "roleCode": "DF",
        "minutes": 1990,
        "matches": 23,
        "starts": 20,
        "subbedIn": 3,
        "goals": 0,
        "assists": 0,
        "contractExpiration": "2026-12-31"
      },
      {
        "playerId": 6200,
        "name": "J. Erabi",
        "firstName": "Jusef",
        "lastName": "Erabi",
        "birthDate": "2003-06-08",
        "birthYear": 2003,
        "age": 21,
        "ageBand": "u19u21",
        "roleName": "Forward",
        "roleCode": "FW",
        "minutes": 1806,
        "matches": 23,
        "starts": 18,
        "subbedIn": 5,
        "goals": 8,
        "assists": 2,
        "contractExpiration": "2029-06-30"
      },
      {
        "playerId": 6467,
        "name": "T. Bazoumana",
        "firstName": "Touré",
        "lastName": "Bazoumana",
        "birthDate": "2006-03-02",
        "birthYear": 2006,
        "age": 18,
        "ageBand": "u18",
        "roleName": "Forward",
        "roleCode": "FW",
        "minutes": 1783,
        "matches": 23,
        "starts": 20,
        "subbedIn": 3,
        "goals": 9,
        "assists": 2,
        "contractExpiration": "2029-06-30"
      },
      {
        "playerId": 6196,
        "name": "M. Karlsson",
        "firstName": "Markus",
        "lastName": "Karlsson",
        "birthDate": "2004-01-20",
        "birthYear": 2004,
        "age": 20,
        "ageBand": "u19u21",
        "roleName": "Midfielder",
        "roleCode": "MD",
        "minutes": 1727,
        "matches": 25,
        "starts": 19,
        "subbedIn": 6,
        "goals": 0,
        "assists": 2,
        "contractExpiration": "2029-12-31"
      },
      {
        "playerId": 6552,
        "name": "V. Eriksson",
        "firstName": "Victor",
        "lastName": "Eriksson",
        "birthDate": "2000-09-17",
        "birthYear": 2000,
        "age": 24,
        "ageBand": "peak",
        "roleName": "Defender",
        "roleCode": "DF",
        "minutes": 1677,
        "matches": 17,
        "starts": 17,
        "subbedIn": 0,
        "goals": 0,
        "assists": 0,
        "contractExpiration": "2028-12-31"
      },
      {
        "playerId": 6186,
        "name": "F. Hammar",
        "firstName": "Fredrik",
        "lastName": "Hammar",
        "birthDate": "2001-02-26",
        "birthYear": 2001,
        "age": 23,
        "ageBand": "u22u23",
        "roleName": "Midfielder",
        "roleCode": "MD",
        "minutes": 1617,
        "matches": 25,
        "starts": 15,
        "subbedIn": 10,
        "goals": 0,
        "assists": 0,
        "contractExpiration": "2028-06-30"
      },
      {
        "playerId": 6569,
        "name": "W. Hahn",
        "firstName": "Warner",
        "lastName": "Hahn",
        "birthDate": "1992-06-15",
        "birthYear": 1992,
        "age": 32,
        "ageBand": "twilight",
        "roleName": "Goalkeeper",
        "roleCode": "GK",
        "minutes": 1468,
        "matches": 15,
        "starts": 15,
        "subbedIn": 0,
        "goals": 0,
        "assists": 0,
        "contractExpiration": "2027-12-31"
      },
      {
        "playerId": 6190,
        "name": "O. Dovin",
        "firstName": "Oliver",
        "lastName": "Dovin",
        "birthDate": "2002-07-11",
        "birthYear": 2002,
        "age": 22,
        "ageBand": "u22u23",
        "roleName": "Goalkeeper",
        "roleCode": "GK",
        "minutes": 1282,
        "matches": 13,
        "starts": 13,
        "subbedIn": 0,
        "goals": 0,
        "assists": 0,
        "contractExpiration": "2028-06-30"
      },
      {
        "playerId": 6182,
        "name": "D. Gül",
        "firstName": "Deniz",
        "lastName": "Gül",
        "birthDate": "2004-07-02",
        "birthYear": 2004,
        "age": 20,
        "ageBand": "u19u21",
        "roleName": "Forward",
        "roleCode": "FW",
        "minutes": 1014,
        "matches": 18,
        "starts": 12,
        "subbedIn": 6,
        "goals": 3,
        "assists": 1,
        "contractExpiration": "2029-06-30"
      },
      {
        "playerId": 6199,
        "name": "E. Kurtulus",
        "firstName": "Edvin",
        "lastName": "Kurtulus",
        "birthDate": "2000-03-05",
        "birthYear": 2000,
        "age": 24,
        "ageBand": "peak",
        "roleName": "Defender",
        "roleCode": "DF",
        "minutes": 1004,
        "matches": 12,
        "starts": 11,
        "subbedIn": 1,
        "goals": 1,
        "assists": 1,
        "contractExpiration": "2027-06-30"
      },
      {
        "playerId": 6563,
        "name": "I. Fofana",
        "firstName": "Ibrahima",
        "lastName": "Breze Fofana",
        "birthDate": "2002-08-15",
        "birthYear": 2002,
        "age": 22,
        "ageBand": "u22u23",
        "roleName": "Midfielder",
        "roleCode": "MD",
        "minutes": 836,
        "matches": 13,
        "starts": 8,
        "subbedIn": 5,
        "goals": 0,
        "assists": 1,
        "contractExpiration": "2029-12-31"
      },
      {
        "playerId": 6197,
        "name": "Montader Madjed",
        "firstName": "Montader",
        "lastName": "Madjed",
        "birthDate": "2005-04-24",
        "birthYear": 2005,
        "age": 19,
        "ageBand": "u19u21",
        "roleName": "Forward",
        "roleCode": "FW",
        "minutes": 680,
        "matches": 15,
        "starts": 7,
        "subbedIn": 8,
        "goals": 0,
        "assists": 3,
        "contractExpiration": "2028-12-31"
      },
      {
        "playerId": 6183,
        "name": "V. Djukanović",
        "firstName": "Viktor",
        "lastName": "Djukanović",
        "birthDate": "2004-01-29",
        "birthYear": 2004,
        "age": 20,
        "ageBand": "u19u21",
        "roleName": "Midfielder",
        "roleCode": "MD",
        "minutes": 612,
        "matches": 12,
        "starts": 6,
        "subbedIn": 6,
        "goals": 2,
        "assists": 1,
        "contractExpiration": "2027-12-31"
      },
      {
        "playerId": 6188,
        "name": "M. Fenger",
        "firstName": "Mads",
        "lastName": "Fenger",
        "birthDate": "1990-09-10",
        "birthYear": 1990,
        "age": 34,
        "ageBand": "twilight",
        "roleName": "Defender",
        "roleCode": "DF",
        "minutes": 564,
        "matches": 13,
        "starts": 5,
        "subbedIn": 8,
        "goals": 0,
        "assists": 0,
        "contractExpiration": "2026-06-30"
      },
      {
        "playerId": 6198,
        "name": "A. Boudah",
        "firstName": "Abdelrahman",
        "lastName": "Boudah Saidi",
        "birthDate": "1999-08-13",
        "birthYear": 1999,
        "age": 25,
        "ageBand": "peak",
        "roleName": "Forward",
        "roleCode": "FW",
        "minutes": 461,
        "matches": 10,
        "starts": 4,
        "subbedIn": 6,
        "goals": 1,
        "assists": 0,
        "contractExpiration": "2027-06-30"
      },
      {
        "playerId": 6513,
        "name": "Marc Llinares",
        "firstName": "Marc",
        "lastName": "Llinares Barragán",
        "birthDate": "1999-08-26",
        "birthYear": 1999,
        "age": 25,
        "ageBand": "peak",
        "roleName": "Defender",
        "roleCode": "DF",
        "minutes": 383,
        "matches": 10,
        "starts": 2,
        "subbedIn": 8,
        "goals": 1,
        "assists": 0,
        "contractExpiration": "2026-06-30"
      },
      {
        "playerId": 6201,
        "name": "S. Strand",
        "firstName": "Simon",
        "lastName": "Strand",
        "birthDate": "1993-05-25",
        "birthYear": 1993,
        "age": 31,
        "ageBand": "twilight",
        "roleName": "Defender",
        "roleCode": "DF",
        "minutes": 306,
        "matches": 14,
        "starts": 0,
        "subbedIn": 14,
        "goals": 0,
        "assists": 0,
        "contractExpiration": "2027-12-31"
      },
      {
        "playerId": 6194,
        "name": "D. Blažević",
        "firstName": "Davor",
        "lastName": "Blažević",
        "birthDate": "1993-02-07",
        "birthYear": 1993,
        "age": 31,
        "ageBand": "twilight",
        "roleName": "Goalkeeper",
        "roleCode": "GK",
        "minutes": 207,
        "matches": 2,
        "starts": 2,
        "subbedIn": 0,
        "goals": 0,
        "assists": 0,
        "contractExpiration": "2027-12-31"
      },
      {
        "playerId": 6187,
        "name": "F. Winther",
        "firstName": "Frederik",
        "lastName": "Winther",
        "birthDate": "2001-01-04",
        "birthYear": 2001,
        "age": 23,
        "ageBand": "u22u23",
        "roleName": "Defender",
        "roleCode": "DF",
        "minutes": 184,
        "matches": 2,
        "starts": 2,
        "subbedIn": 0,
        "goals": 0,
        "assists": 0,
        "contractExpiration": "2027-12-31"
      },
      {
        "playerId": 6534,
        "name": "D. Collander",
        "firstName": "Dennis",
        "lastName": "Collander",
        "birthDate": "2002-05-09",
        "birthYear": 2002,
        "age": 22,
        "ageBand": "u22u23",
        "roleName": "Midfielder",
        "roleCode": "MD",
        "minutes": 152,
        "matches": 7,
        "starts": 1,
        "subbedIn": 6,
        "goals": 0,
        "assists": 0,
        "contractExpiration": "2026-07-14"
      },
      {
        "playerId": 6618,
        "name": "S. Clemmensen",
        "firstName": "Sebastian",
        "lastName": "Clemmensen",
        "birthDate": "2003-09-01",
        "birthYear": 2003,
        "age": 21,
        "ageBand": "u19u21",
        "roleName": "Forward",
        "roleCode": "FW",
        "minutes": 91,
        "matches": 3,
        "starts": 1,
        "subbedIn": 2,
        "goals": 0,
        "assists": 0,
        "contractExpiration": "2028-12-31"
      },
      {
        "playerId": 6620,
        "name": "A. Lahdo",
        "firstName": "Adrian",
        "lastName": "Lahdo",
        "birthDate": "2007-12-26",
        "birthYear": 2007,
        "age": 17,
        "ageBand": "u18",
        "roleName": "Midfielder",
        "roleCode": "MD",
        "minutes": 74,
        "matches": 2,
        "starts": 1,
        "subbedIn": 1,
        "goals": 0,
        "assists": 0,
        "contractExpiration": "2031-06-30"
      },
      {
        "playerId": 6553,
        "name": "D. Teah",
        "firstName": "Divine Roosevelt",
        "lastName": "Teah",
        "birthDate": "2006-04-19",
        "birthYear": 2006,
        "age": 18,
        "ageBand": "u18",
        "roleName": "Midfielder",
        "roleCode": "MD",
        "minutes": 72,
        "matches": 7,
        "starts": 0,
        "subbedIn": 7,
        "goals": 0,
        "assists": 0,
        "contractExpiration": "2029-12-31"
      },
      {
        "playerId": 6195,
        "name": "K. Gyamfi",
        "firstName": "Kingsley",
        "lastName": "Gyamfi",
        "birthDate": "2004-03-15",
        "birthYear": 2004,
        "age": 20,
        "ageBand": "u19u21",
        "roleName": "Defender",
        "roleCode": "DF",
        "minutes": 53,
        "matches": 4,
        "starts": 0,
        "subbedIn": 4,
        "goals": 0,
        "assists": 0,
        "contractExpiration": "2028-12-31"
      },
      {
        "playerId": 6512,
        "name": "M. Rafferty",
        "firstName": "Marcus",
        "lastName": "Rafferty",
        "birthDate": "2004-10-01",
        "birthYear": 2004,
        "age": 20,
        "ageBand": "u19u21",
        "roleName": "Midfielder",
        "roleCode": "MD",
        "minutes": 23,
        "matches": 1,
        "starts": 0,
        "subbedIn": 1,
        "goals": 0,
        "assists": 0,
        "contractExpiration": "2027-12-31"
      },
      {
        "playerId": 6621,
        "name": "J. Kanga",
        "firstName": "Jardell",
        "lastName": "Kanga",
        "birthDate": "2005-12-13",
        "birthYear": 2005,
        "age": 19,
        "ageBand": "u19u21",
        "roleName": "Midfielder",
        "roleCode": "MD",
        "minutes": 9,
        "matches": 1,
        "starts": 0,
        "subbedIn": 1,
        "goals": 0,
        "assists": 0,
        "contractExpiration": "2027-12-31"
      },
      {
        "playerId": 6570,
        "name": "G. Elezaj",
        "firstName": "Gent",
        "lastName": "Elezaj",
        "birthDate": "2005-04-11",
        "birthYear": 2005,
        "age": 19,
        "ageBand": "u19u21",
        "roleName": "Midfielder",
        "roleCode": "MD",
        "minutes": 3,
        "matches": 1,
        "starts": 0,
        "subbedIn": 1,
        "goals": 0,
        "assists": 0,
        "contractExpiration": "2028-12-31"
      },
      {
        "playerId": 6193,
        "name": "A. Kralj",
        "firstName": "Anton",
        "lastName": "Kralj",
        "birthDate": "1998-03-12",
        "birthYear": 1998,
        "age": 26,
        "ageBand": "peak",
        "roleName": "Defender",
        "roleCode": "DF",
        "minutes": 0,
        "matches": 0,
        "starts": 0,
        "subbedIn": 0,
        "goals": 0,
        "assists": 0,
        "contractExpiration": "2025-12-31"
      },
      {
        "playerId": 6646,
        "name": "E. Fischerström",
        "firstName": "Elton",
        "lastName": "Fischerström Opančar",
        "birthDate": "2007-01-02",
        "birthYear": 2007,
        "age": 17,
        "ageBand": "u18",
        "roleName": "Goalkeeper",
        "roleCode": "GK",
        "minutes": 0,
        "matches": 0,
        "starts": 0,
        "subbedIn": 0,
        "goals": 0,
        "assists": 0,
        "contractExpiration": "2029-12-31"
      },
      {
        "playerId": 6564,
        "name": "S. Selin",
        "firstName": "Sebastian",
        "lastName": "Selin",
        "birthDate": "2003-01-11",
        "birthYear": 2003,
        "age": 21,
        "ageBand": "u19u21",
        "roleName": "Goalkeeper",
        "roleCode": "GK",
        "minutes": 0,
        "matches": 0,
        "starts": 0,
        "subbedIn": 0,
        "goals": 0,
        "assists": 0,
        "contractExpiration": "2026-12-31"
      },
      {
        "playerId": 6647,
        "name": "W. Lindberg Uhrstrom",
        "firstName": "Wilson",
        "lastName": "Lindberg Uhrstrom",
        "birthDate": "2006-03-23",
        "birthYear": 2006,
        "age": 18,
        "ageBand": "u18",
        "minutes": 0,
        "matches": 0,
        "starts": 0,
        "subbedIn": 0,
        "goals": 0,
        "assists": 0,
        "contractExpiration": "2028-12-31"
      }
    ]
  },
  {
    "season": 2025,
    "label": "2025",
    "status": "Hel säsong",
    "teamName": "Hammarby IF",
    "sourceUrl": "https://bolldata.se/trupper?season_name=2025",
    "sourceApiUrl": "https://bolldata.se/api/team-advanced/?season_name=2025",
    "players": [
      {
        "playerId": 5695,
        "name": "V. Eriksson",
        "firstName": "Victor",
        "lastName": "Eriksson",
        "birthDate": "2000-09-17",
        "birthYear": 2000,
        "age": 25,
        "ageBand": "peak",
        "roleName": "Defender",
        "roleCode": "DF",
        "minutes": 2862,
        "matches": 29,
        "starts": 29,
        "subbedIn": 0,
        "goals": 2,
        "assists": 1,
        "contractExpiration": "2028-12-31"
      },
      {
        "playerId": 5696,
        "name": "W. Hahn",
        "firstName": "Warner",
        "lastName": "Hahn",
        "birthDate": "1992-06-15",
        "birthYear": 1992,
        "age": 33,
        "ageBand": "twilight",
        "roleName": "Goalkeeper",
        "roleCode": "GK",
        "minutes": 2853,
        "matches": 29,
        "starts": 29,
        "subbedIn": 0,
        "goals": 0,
        "assists": 0,
        "contractExpiration": "2027-12-31"
      },
      {
        "playerId": 5698,
        "name": "N. Besara",
        "firstName": "Nahir",
        "lastName": "Besara",
        "birthDate": "1991-02-25",
        "birthYear": 1991,
        "age": 34,
        "ageBand": "twilight",
        "roleName": "Midfielder",
        "roleCode": "MD",
        "minutes": 2719,
        "matches": 30,
        "starts": 29,
        "subbedIn": 1,
        "goals": 17,
        "assists": 2,
        "contractExpiration": "2027-12-31"
      },
      {
        "playerId": 5692,
        "name": "M. Karlsson",
        "firstName": "Markus",
        "lastName": "Karlsson",
        "birthDate": "2004-01-20",
        "birthYear": 2004,
        "age": 21,
        "ageBand": "u19u21",
        "roleName": "Midfielder",
        "roleCode": "MD",
        "minutes": 2710,
        "matches": 28,
        "starts": 28,
        "subbedIn": 0,
        "goals": 3,
        "assists": 1,
        "contractExpiration": "2029-12-31"
      },
      {
        "playerId": 5699,
        "name": "T. Tekie",
        "firstName": "Tesfaldet",
        "lastName": "Tekie",
        "birthDate": "1997-06-04",
        "birthYear": 1997,
        "age": 28,
        "ageBand": "peak",
        "roleName": "Midfielder",
        "roleCode": "MD",
        "minutes": 2362,
        "matches": 27,
        "starts": 24,
        "subbedIn": 3,
        "goals": 1,
        "assists": 3,
        "contractExpiration": "2026-12-31"
      },
      {
        "playerId": 5693,
        "name": "P. Vagić",
        "firstName": "Pavle",
        "lastName": "Vagić",
        "birthDate": "2000-01-24",
        "birthYear": 2000,
        "age": 25,
        "ageBand": "peak",
        "roleName": "Defender",
        "roleCode": "DF",
        "minutes": 2351,
        "matches": 25,
        "starts": 25,
        "subbedIn": 0,
        "goals": 0,
        "assists": 0,
        "contractExpiration": "2026-12-31"
      },
      {
        "playerId": 5691,
        "name": "H. Skoglund",
        "firstName": "Hampus",
        "lastName": "Skoglund",
        "birthDate": "2004-03-01",
        "birthYear": 2004,
        "age": 21,
        "ageBand": "u19u21",
        "roleName": "Defender",
        "roleCode": "DF",
        "minutes": 2290,
        "matches": 27,
        "starts": 25,
        "subbedIn": 2,
        "goals": 0,
        "assists": 3,
        "contractExpiration": "2029-12-31"
      },
      {
        "playerId": 5689,
        "name": "P. Abraham",
        "firstName": "Paulos",
        "lastName": "Abraham",
        "birthDate": "2002-07-16",
        "birthYear": 2002,
        "age": 23,
        "ageBand": "u22u23",
        "roleName": "Forward",
        "roleCode": "FW",
        "minutes": 1885,
        "matches": 27,
        "starts": 21,
        "subbedIn": 6,
        "goals": 8,
        "assists": 3,
        "contractExpiration": "2028-12-31"
      },
      {
        "playerId": 5694,
        "name": "S. Pinas",
        "firstName": "Shaquille",
        "lastName": "Pinas",
        "birthDate": "1998-03-19",
        "birthYear": 1998,
        "age": 27,
        "ageBand": "peak",
        "roleName": "Defender",
        "roleCode": "DF",
        "minutes": 1831,
        "matches": 19,
        "starts": 19,
        "subbedIn": 0,
        "goals": 2,
        "assists": 0,
        "contractExpiration": "2028-06-30"
      },
      {
        "playerId": 5690,
        "name": "S. Tounekti",
        "firstName": "Sebastian",
        "lastName": "Tounekti",
        "birthDate": "2002-07-13",
        "birthYear": 2002,
        "age": 23,
        "ageBand": "u22u23",
        "roleName": "Forward",
        "roleCode": "FW",
        "minutes": 1675,
        "matches": 21,
        "starts": 20,
        "subbedIn": 1,
        "goals": 2,
        "assists": 4,
        "contractExpiration": "2030-05-31"
      },
      {
        "playerId": 5706,
        "name": "Montader Madjed",
        "firstName": "Montader",
        "lastName": "Madjed",
        "birthDate": "2005-04-24",
        "birthYear": 2005,
        "age": 20,
        "ageBand": "u19u21",
        "roleName": "Forward",
        "roleCode": "FW",
        "minutes": 1517,
        "matches": 26,
        "starts": 17,
        "subbedIn": 9,
        "goals": 7,
        "assists": 5,
        "contractExpiration": "2028-12-31"
      },
      {
        "playerId": 6009,
        "name": "F. Winther",
        "firstName": "Frederik",
        "lastName": "Winther",
        "birthDate": "2001-01-04",
        "birthYear": 2001,
        "age": 24,
        "ageBand": "peak",
        "roleName": "Defender",
        "roleCode": "DF",
        "minutes": 1162,
        "matches": 15,
        "starts": 11,
        "subbedIn": 4,
        "goals": 0,
        "assists": 0,
        "contractExpiration": "2027-12-31"
      },
      {
        "playerId": 5697,
        "name": "J. Erabi",
        "firstName": "Jusef",
        "lastName": "Erabi",
        "birthDate": "2003-06-08",
        "birthYear": 2003,
        "age": 22,
        "ageBand": "u22u23",
        "roleName": "Forward",
        "roleCode": "FW",
        "minutes": 991,
        "matches": 18,
        "starts": 10,
        "subbedIn": 8,
        "goals": 4,
        "assists": 1,
        "contractExpiration": "2029-06-30"
      },
      {
        "playerId": 5701,
        "name": "I. Fofana",
        "firstName": "Ibrahima",
        "lastName": "Breze Fofana",
        "birthDate": "2002-08-15",
        "birthYear": 2002,
        "age": 23,
        "ageBand": "u22u23",
        "roleName": "Midfielder",
        "roleCode": "MD",
        "minutes": 966,
        "matches": 21,
        "starts": 9,
        "subbedIn": 12,
        "goals": 1,
        "assists": 0,
        "contractExpiration": "2029-12-31"
      },
      {
        "playerId": 5704,
        "name": "A. Boudah",
        "firstName": "Abdelrahman",
        "lastName": "Boudah Saidi",
        "birthDate": "1999-08-13",
        "birthYear": 1999,
        "age": 26,
        "ageBand": "peak",
        "roleName": "Forward",
        "roleCode": "FW",
        "minutes": 884,
        "matches": 17,
        "starts": 6,
        "subbedIn": 11,
        "goals": 4,
        "assists": 1,
        "contractExpiration": "2027-06-30"
      },
      {
        "playerId": 6016,
        "name": "O. Johansson",
        "firstName": "Oscar Nils Per",
        "lastName": "Johansson Schellhas",
        "birthDate": "1995-05-06",
        "birthYear": 1995,
        "age": 30,
        "ageBand": "twilight",
        "roleName": "Midfielder",
        "roleCode": "MD",
        "minutes": 723,
        "matches": 14,
        "starts": 6,
        "subbedIn": 8,
        "goals": 0,
        "assists": 1,
        "contractExpiration": "2026-12-31"
      },
      {
        "playerId": 5864,
        "name": "F. Adjei",
        "firstName": "Frank Junior",
        "lastName": "Adjei",
        "birthDate": "2004-03-20",
        "birthYear": 2004,
        "age": 21,
        "ageBand": "u19u21",
        "roleName": "Forward",
        "roleCode": "FW",
        "minutes": 557,
        "matches": 11,
        "starts": 6,
        "subbedIn": 5,
        "goals": 1,
        "assists": 0,
        "contractExpiration": "2029-12-31"
      },
      {
        "playerId": 5707,
        "name": "S. Strand",
        "firstName": "Simon",
        "lastName": "Strand",
        "birthDate": "1993-05-25",
        "birthYear": 1993,
        "age": 32,
        "ageBand": "twilight",
        "roleName": "Defender",
        "roleCode": "DF",
        "minutes": 506,
        "matches": 21,
        "starts": 3,
        "subbedIn": 18,
        "goals": 2,
        "assists": 0,
        "contractExpiration": "2027-12-31"
      },
      {
        "playerId": 5705,
        "name": "A. Lahdo",
        "firstName": "Adrian",
        "lastName": "Lahdo",
        "birthDate": "2007-12-26",
        "birthYear": 2007,
        "age": 18,
        "ageBand": "u18",
        "roleName": "Midfielder",
        "roleCode": "MD",
        "minutes": 441,
        "matches": 12,
        "starts": 5,
        "subbedIn": 7,
        "goals": 1,
        "assists": 3,
        "contractExpiration": "2031-06-30"
      },
      {
        "playerId": 5703,
        "name": "M. Kaboré",
        "firstName": "Moise Elohim",
        "lastName": "Kaboré",
        "birthDate": "2006-12-20",
        "birthYear": 2006,
        "age": 19,
        "ageBand": "u19u21",
        "roleName": "Forward",
        "roleCode": "FW",
        "minutes": 373,
        "matches": 14,
        "starts": 3,
        "subbedIn": 11,
        "goals": 2,
        "assists": 0,
        "contractExpiration": "2029-12-31"
      },
      {
        "playerId": 6093,
        "name": "O. Okeke",
        "firstName": "Obilor Denzel",
        "lastName": "Okeke",
        "birthDate": "2002-07-23",
        "birthYear": 2002,
        "age": 23,
        "ageBand": "u22u23",
        "roleName": "Forward",
        "roleCode": "FW",
        "minutes": 315,
        "matches": 9,
        "starts": 2,
        "subbedIn": 7,
        "goals": 0,
        "assists": 1,
        "contractExpiration": "2029-12-31"
      },
      {
        "playerId": 5702,
        "name": "J. Ortmark",
        "firstName": "Jacob",
        "lastName": "Ortmark",
        "birthDate": "1997-08-29",
        "birthYear": 1997,
        "age": 28,
        "ageBand": "peak",
        "roleName": "Midfielder",
        "roleCode": "MD",
        "minutes": 163,
        "matches": 9,
        "starts": 1,
        "subbedIn": 8,
        "goals": 0,
        "assists": 1,
        "contractExpiration": "2026-12-31"
      },
      {
        "playerId": 5942,
        "name": "J. Karlsson",
        "firstName": "Jonathan",
        "lastName": "Karlsson",
        "birthDate": "2003-11-27",
        "birthYear": 2003,
        "age": 22,
        "ageBand": "u22u23",
        "roleName": "Defender",
        "roleCode": "DF",
        "minutes": 127,
        "matches": 8,
        "starts": 0,
        "subbedIn": 8,
        "goals": 0,
        "assists": 0,
        "contractExpiration": "2029-12-31"
      },
      {
        "playerId": 5708,
        "name": "W. Lindberg Uhrstrom",
        "firstName": "Wilson",
        "lastName": "Lindberg Uhrstrom",
        "birthDate": "2006-03-23",
        "birthYear": 2006,
        "age": 19,
        "ageBand": "u19u21",
        "minutes": 108,
        "matches": 6,
        "starts": 1,
        "subbedIn": 5,
        "goals": 0,
        "assists": 0,
        "contractExpiration": "2028-12-31"
      },
      {
        "playerId": 5700,
        "name": "F. Jakobsson",
        "firstName": "Felix",
        "lastName": "Jakobsson",
        "birthDate": "1999-09-16",
        "birthYear": 1999,
        "age": 26,
        "ageBand": "peak",
        "roleName": "Goalkeeper",
        "roleCode": "GK",
        "minutes": 102,
        "matches": 1,
        "starts": 1,
        "subbedIn": 0,
        "goals": 0,
        "assists": 0,
        "contractExpiration": "2028-12-31"
      },
      {
        "playerId": 6116,
        "name": "N. Vasić",
        "firstName": "Nikola",
        "lastName": "Vasić",
        "birthDate": "1991-10-04",
        "birthYear": 1991,
        "age": 34,
        "ageBand": "twilight",
        "roleName": "Forward",
        "roleCode": "FW",
        "minutes": 27,
        "matches": 2,
        "starts": 0,
        "subbedIn": 2,
        "goals": 0,
        "assists": 0,
        "contractExpiration": "2026-12-31"
      },
      {
        "playerId": 6108,
        "name": "N. Persson",
        "firstName": "Noah",
        "lastName": "Persson",
        "birthDate": "2003-07-16",
        "birthYear": 2003,
        "age": 22,
        "ageBand": "u22u23",
        "roleName": "Defender",
        "roleCode": "DF",
        "minutes": 17,
        "matches": 1,
        "starts": 0,
        "subbedIn": 1,
        "goals": 0,
        "assists": 0,
        "contractExpiration": "2029-12-31"
      },
      {
        "playerId": 6123,
        "name": "E. Fischerström",
        "firstName": "Elton",
        "lastName": "Fischerström Opančar",
        "birthDate": "2007-01-02",
        "birthYear": 2007,
        "age": 18,
        "ageBand": "u18",
        "roleName": "Goalkeeper",
        "roleCode": "GK",
        "minutes": 0,
        "matches": 0,
        "starts": 0,
        "subbedIn": 0,
        "goals": 0,
        "assists": 0,
        "contractExpiration": "2029-12-31"
      },
      {
        "playerId": 5972,
        "name": "G. Elezaj",
        "firstName": "Gent",
        "lastName": "Elezaj",
        "birthDate": "2005-04-11",
        "birthYear": 2005,
        "age": 20,
        "ageBand": "u19u21",
        "roleName": "Midfielder",
        "roleCode": "MD",
        "minutes": 0,
        "matches": 0,
        "starts": 0,
        "subbedIn": 0,
        "goals": 0,
        "assists": 0,
        "contractExpiration": "2028-12-31"
      }
    ]
  },
  {
    "season": 2026,
    "label": "2026",
    "status": "Pågående säsong",
    "teamName": "Hammarby IF",
    "sourceUrl": "https://bolldata.se/trupper?season_name=2026",
    "sourceApiUrl": "https://bolldata.se/api/team-advanced/?season_name=2026",
    "players": [
      {
        "playerId": 9926,
        "name": "W. Hahn",
        "firstName": "Warner",
        "lastName": "Hahn",
        "birthDate": "1992-06-15",
        "birthYear": 1992,
        "age": 34,
        "ageBand": "twilight",
        "roleName": "Goalkeeper",
        "roleCode": "GK",
        "minutes": 1067,
        "matches": 11,
        "starts": 11,
        "subbedIn": 0,
        "goals": 0,
        "assists": 0,
        "contractExpiration": "2027-12-31"
      },
      {
        "playerId": 9941,
        "name": "M. Karlsson",
        "firstName": "Markus",
        "lastName": "Karlsson",
        "birthDate": "2004-01-20",
        "birthYear": 2004,
        "age": 22,
        "ageBand": "u22u23",
        "roleName": "Midfielder",
        "roleCode": "MD",
        "minutes": 1060,
        "matches": 11,
        "starts": 11,
        "subbedIn": 0,
        "goals": 0,
        "assists": 1,
        "contractExpiration": "2029-12-31"
      },
      {
        "playerId": 9932,
        "name": "V. Eriksson",
        "firstName": "Victor",
        "lastName": "Eriksson",
        "birthDate": "2000-09-17",
        "birthYear": 2000,
        "age": 26,
        "ageBand": "peak",
        "roleName": "Defender",
        "roleCode": "DF",
        "minutes": 1053,
        "matches": 11,
        "starts": 11,
        "subbedIn": 0,
        "goals": 1,
        "assists": 0,
        "contractExpiration": "2028-12-31"
      },
      {
        "playerId": 9931,
        "name": "F. Winther",
        "firstName": "Frederik",
        "lastName": "Winther",
        "birthDate": "2001-01-04",
        "birthYear": 2001,
        "age": 25,
        "ageBand": "peak",
        "roleName": "Defender",
        "roleCode": "DF",
        "minutes": 1043,
        "matches": 11,
        "starts": 11,
        "subbedIn": 0,
        "goals": 0,
        "assists": 1,
        "contractExpiration": "2027-12-31"
      },
      {
        "playerId": 9944,
        "name": "H. Skoglund",
        "firstName": "Hampus",
        "lastName": "Skoglund",
        "birthDate": "2004-03-01",
        "birthYear": 2004,
        "age": 22,
        "ageBand": "u22u23",
        "roleName": "Defender",
        "roleCode": "DF",
        "minutes": 932,
        "matches": 10,
        "starts": 10,
        "subbedIn": 0,
        "goals": 0,
        "assists": 2,
        "contractExpiration": "2029-12-31"
      },
      {
        "playerId": 9925,
        "name": "N. Besara",
        "firstName": "Nahir",
        "lastName": "Besara",
        "birthDate": "1991-02-25",
        "birthYear": 1991,
        "age": 35,
        "ageBand": "twilight",
        "roleName": "Midfielder",
        "roleCode": "MD",
        "minutes": 909,
        "matches": 11,
        "starts": 10,
        "subbedIn": 1,
        "goals": 5,
        "assists": 5,
        "contractExpiration": "2027-12-31"
      },
      {
        "playerId": 9937,
        "name": "P. Abraham",
        "firstName": "Paulos",
        "lastName": "Abraham",
        "birthDate": "2002-07-16",
        "birthYear": 2002,
        "age": 24,
        "ageBand": "peak",
        "roleName": "Forward",
        "roleCode": "FW",
        "minutes": 869,
        "matches": 11,
        "starts": 10,
        "subbedIn": 1,
        "goals": 5,
        "assists": 2,
        "contractExpiration": "2028-12-31"
      },
      {
        "playerId": 9936,
        "name": "Montader Madjed",
        "firstName": "Montader",
        "lastName": "Madjed",
        "birthDate": "2005-04-24",
        "birthYear": 2005,
        "age": 21,
        "ageBand": "u19u21",
        "roleName": "Forward",
        "roleCode": "FW",
        "minutes": 837,
        "matches": 11,
        "starts": 10,
        "subbedIn": 1,
        "goals": 2,
        "assists": 0,
        "contractExpiration": "2028-12-31"
      },
      {
        "playerId": 9933,
        "name": "V. Lind",
        "firstName": "Victor",
        "lastName": "Stange Lind",
        "birthDate": "2003-06-12",
        "birthYear": 2003,
        "age": 23,
        "ageBand": "u22u23",
        "roleName": "Forward",
        "roleCode": "FW",
        "minutes": 785,
        "matches": 11,
        "starts": 9,
        "subbedIn": 2,
        "goals": 5,
        "assists": 2,
        "contractExpiration": "2029-12-31"
      },
      {
        "playerId": 9927,
        "name": "O. Johansson",
        "firstName": "Oscar Nils Per",
        "lastName": "Johansson Schellhas",
        "birthDate": "1995-05-06",
        "birthYear": 1995,
        "age": 31,
        "ageBand": "twilight",
        "roleName": "Midfielder",
        "roleCode": "MD",
        "minutes": 644,
        "matches": 10,
        "starts": 7,
        "subbedIn": 3,
        "goals": 0,
        "assists": 2,
        "contractExpiration": "2026-12-31"
      },
      {
        "playerId": 9938,
        "name": "N. Persson",
        "firstName": "Noah",
        "lastName": "Persson",
        "birthDate": "2003-07-16",
        "birthYear": 2003,
        "age": 23,
        "ageBand": "u22u23",
        "roleName": "Defender",
        "roleCode": "DF",
        "minutes": 614,
        "matches": 11,
        "starts": 6,
        "subbedIn": 5,
        "goals": 1,
        "assists": 1,
        "contractExpiration": "2029-12-31"
      },
      {
        "playerId": 9935,
        "name": "I. Fofana",
        "firstName": "Ibrahima",
        "lastName": "Breze Fofana",
        "birthDate": "2002-08-15",
        "birthYear": 2002,
        "age": 24,
        "ageBand": "peak",
        "roleName": "Midfielder",
        "roleCode": "MD",
        "minutes": 594,
        "matches": 8,
        "starts": 6,
        "subbedIn": 2,
        "goals": 1,
        "assists": 0,
        "contractExpiration": "2029-12-31"
      },
      {
        "playerId": 9942,
        "name": "F. Adjei",
        "firstName": "Frank Junior",
        "lastName": "Adjei",
        "birthDate": "2004-03-20",
        "birthYear": 2004,
        "age": 22,
        "ageBand": "u22u23",
        "roleName": "Forward",
        "roleCode": "FW",
        "minutes": 372,
        "matches": 9,
        "starts": 3,
        "subbedIn": 6,
        "goals": 1,
        "assists": 2,
        "contractExpiration": "2029-12-31"
      },
      {
        "playerId": 9928,
        "name": "T. Tekie",
        "firstName": "Tesfaldet",
        "lastName": "Tekie",
        "birthDate": "1997-06-04",
        "birthYear": 1997,
        "age": 29,
        "ageBand": "peak",
        "roleName": "Midfielder",
        "roleCode": "MD",
        "minutes": 280,
        "matches": 5,
        "starts": 3,
        "subbedIn": 2,
        "goals": 0,
        "assists": 0,
        "contractExpiration": "2026-12-31"
      },
      {
        "playerId": 9939,
        "name": "O. Hagen",
        "firstName": "Oliver Jordan",
        "lastName": "Hagen",
        "birthDate": "2006-06-09",
        "birthYear": 2006,
        "age": 20,
        "ageBand": "u19u21",
        "roleName": "Midfielder",
        "roleCode": "MD",
        "minutes": 211,
        "matches": 9,
        "starts": 1,
        "subbedIn": 8,
        "goals": 0,
        "assists": 0,
        "contractExpiration": null
      },
      {
        "playerId": 9943,
        "name": "M. Kaboré",
        "firstName": "Moise Elohim",
        "lastName": "Kaboré",
        "birthDate": "2006-12-20",
        "birthYear": 2006,
        "age": 20,
        "ageBand": "u19u21",
        "roleName": "Forward",
        "roleCode": "FW",
        "minutes": 181,
        "matches": 5,
        "starts": 2,
        "subbedIn": 3,
        "goals": 0,
        "assists": 0,
        "contractExpiration": "2029-12-31"
      },
      {
        "playerId": 9930,
        "name": "N. Vasić",
        "firstName": "Nikola",
        "lastName": "Vasić",
        "birthDate": "1991-10-04",
        "birthYear": 1991,
        "age": 35,
        "ageBand": "twilight",
        "roleName": "Forward",
        "roleCode": "FW",
        "minutes": 138,
        "matches": 7,
        "starts": 0,
        "subbedIn": 7,
        "goals": 3,
        "assists": 0,
        "contractExpiration": "2026-12-31"
      },
      {
        "playerId": 9940,
        "name": "O. Steinke Brånby",
        "firstName": "Oscar",
        "lastName": "Steinke Brånby",
        "birthDate": "2006-02-07",
        "birthYear": 2006,
        "age": 20,
        "ageBand": "u19u21",
        "roleName": "Midfielder",
        "roleCode": "MD",
        "minutes": 77,
        "matches": 5,
        "starts": 0,
        "subbedIn": 5,
        "goals": 0,
        "assists": 0,
        "contractExpiration": "2030-12-31"
      },
      {
        "playerId": 9946,
        "name": "W. Lindberg Uhrström",
        "firstName": "Wilson Elliot",
        "lastName": "Lindberg Uhrström",
        "birthDate": "2006-03-23",
        "birthYear": 2006,
        "age": 20,
        "ageBand": "u19u21",
        "roleName": "Midfielder",
        "roleCode": "MD",
        "minutes": 35,
        "matches": 3,
        "starts": 0,
        "subbedIn": 3,
        "goals": 0,
        "assists": 1,
        "contractExpiration": "2028-12-31"
      },
      {
        "playerId": 9934,
        "name": "D. Collander",
        "firstName": "Dennis",
        "lastName": "Collander",
        "birthDate": "2002-05-09",
        "birthYear": 2002,
        "age": 24,
        "ageBand": "peak",
        "roleName": "Midfielder",
        "roleCode": "MD",
        "minutes": 12,
        "matches": 2,
        "starts": 0,
        "subbedIn": 2,
        "goals": 0,
        "assists": 0,
        "contractExpiration": "2026-07-14"
      },
      {
        "playerId": 9945,
        "name": "S. Kone",
        "firstName": "Sourou",
        "lastName": "Kone",
        "birthDate": "2008-01-01",
        "birthYear": 2008,
        "age": 18,
        "ageBand": "u18",
        "roleName": "Midfielder",
        "roleCode": "MD",
        "minutes": 4,
        "matches": 1,
        "starts": 0,
        "subbedIn": 1,
        "goals": 0,
        "assists": 0,
        "contractExpiration": null
      },
      {
        "playerId": 10008,
        "name": "B. Hedlöf",
        "firstName": "Björn",
        "lastName": "Hedlöf",
        "birthDate": "2008-07-14",
        "birthYear": 2008,
        "age": 18,
        "ageBand": "u18",
        "roleName": "Midfielder",
        "roleCode": "MD",
        "minutes": 0,
        "matches": 0,
        "starts": 0,
        "subbedIn": 0,
        "goals": 0,
        "assists": 0,
        "contractExpiration": "2027-12-31"
      },
      {
        "playerId": 10020,
        "name": "E. Fischerström",
        "firstName": "Elton",
        "lastName": "Fischerström Opančar",
        "birthDate": "2007-01-02",
        "birthYear": 2007,
        "age": 19,
        "ageBand": "u19u21",
        "roleName": "Goalkeeper",
        "roleCode": "GK",
        "minutes": 0,
        "matches": 0,
        "starts": 0,
        "subbedIn": 0,
        "goals": 0,
        "assists": 0,
        "contractExpiration": "2029-12-31"
      },
      {
        "playerId": 9947,
        "name": "E. Lwampindy Bofua",
        "firstName": "Essayas",
        "lastName": "Lwampindy Bofua",
        "birthDate": "2005-08-10",
        "birthYear": 2005,
        "age": 21,
        "ageBand": "u19u21",
        "roleName": "Defender",
        "roleCode": "DF",
        "minutes": 0,
        "matches": 0,
        "starts": 0,
        "subbedIn": 0,
        "goals": 0,
        "assists": 0,
        "contractExpiration": "2029-12-31"
      },
      {
        "playerId": 9929,
        "name": "F. Jakobsson",
        "firstName": "Felix",
        "lastName": "Jakobsson",
        "birthDate": "1999-09-16",
        "birthYear": 1999,
        "age": 27,
        "ageBand": "peak",
        "roleName": "Goalkeeper",
        "roleCode": "GK",
        "minutes": 0,
        "matches": 0,
        "starts": 0,
        "subbedIn": 0,
        "goals": 0,
        "assists": 0,
        "contractExpiration": "2028-12-31"
      }
    ]
  }
];

export const hammarbySquadAgeStructure2026 = hammarbySquadAgeStructureSeasons.find(
  (season) => season.season === 2026
) ?? hammarbySquadAgeStructureSeasons[hammarbySquadAgeStructureSeasons.length - 1];
