export const matchData = {
  competition: "Allsvenskan",
  round: "Omgång 2",
  date: "13 april 2026",
  time: "19:00",
  referee: "Glenn Nyberg",
  source: "bolldata.se",

  home: {
    name: "IK Sirius",
    shortName: "Sirius",
    logo: "🔵",
    color: "#1d4ed8",
    goals: 2,
  },
  away: {
    name: "Hammarby IF",
    shortName: "Hammarby",
    logo: "🟢",
    color: "#16a34a",
    goals: 0,
  },

  teamStats: [
    { label: "xG", home: 0.96, away: 1.41, format: "decimal" },
    { label: "Avslut", home: 8, away: 16, format: "number" },
    { label: "Skott på mål", home: 3, away: 3, format: "number" },
    { label: "Bollinnehav", home: 32, away: 68, format: "percent" },
    { label: "Passningar", home: 215, away: 608, format: "number" },
    { label: "Passningsprocent", home: 77, away: 88, format: "percent" },
    { label: "Bollkontakter i box", home: 7, away: 22, format: "number" },
    { label: "Hörnor", home: 3, away: 2, format: "number" },
  ],

  keyInsights: [
    {
      title: "xG-dominans",
      description: "Hammarby skapade fler förväntade mål (1.41 vs 0.96) men Sirius var mer effektiva framför mål.",
      type: "tactical" as const,
    },
    {
      title: "Bollinnehavet",
      description: "Hammarby dominerade med 68% bollinnehav men lyckades inte omsätta det till mål.",
      type: "possession" as const,
    },
    {
      title: "Effektivitet",
      description: "Sirius konverterade 25% av sina avslut till mål, medan Hammarby hade 0% trots 16 avslut.",
      type: "efficiency" as const,
    },
    {
      title: "Passningsspelet",
      description: "Hammarby spelade nästan tre gånger så många passningar (608 vs 215) med 88% precision.",
      type: "passing" as const,
    },
  ],

  xgTimeline: [
    { minute: 12, team: "home" as const, xg: 0.08, result: "miss" as const },
    { minute: 18, team: "away" as const, xg: 0.05, result: "miss" as const },
    { minute: 23, team: "away" as const, xg: 0.12, result: "miss" as const },
    { minute: 27, team: "away" as const, xg: 0.03, result: "miss" as const },
    { minute: 31, team: "home" as const, xg: 0.42, result: "goal" as const },
    { minute: 35, team: "away" as const, xg: 0.15, result: "saved" as const },
    { minute: 40, team: "away" as const, xg: 0.08, result: "miss" as const },
    { minute: 44, team: "home" as const, xg: 0.06, result: "miss" as const },
    { minute: 48, team: "away" as const, xg: 0.04, result: "miss" as const },
    { minute: 52, team: "away" as const, xg: 0.22, result: "saved" as const },
    { minute: 56, team: "home" as const, xg: 0.03, result: "miss" as const },
    { minute: 60, team: "away" as const, xg: 0.09, result: "miss" as const },
    { minute: 63, team: "away" as const, xg: 0.06, result: "miss" as const },
    { minute: 67, team: "away" as const, xg: 0.18, result: "saved" as const },
    { minute: 71, team: "home" as const, xg: 0.05, result: "miss" as const },
    { minute: 74, team: "away" as const, xg: 0.11, result: "miss" as const },
    { minute: 78, team: "home" as const, xg: 0.04, result: "miss" as const },
    { minute: 80, team: "away" as const, xg: 0.07, result: "miss" as const },
    { minute: 83, team: "home" as const, xg: 0.15, result: "miss" as const },
    { minute: 85, team: "away" as const, xg: 0.14, result: "miss" as const },
    { minute: 88, team: "home" as const, xg: 0.13, result: "goal" as const },
    { minute: 90, team: "away" as const, xg: 0.07, result: "miss" as const },
  ],

  momentum: [
    { minute: 0, value: 0 },
    { minute: 5, value: -10 },
    { minute: 10, value: -20 },
    { minute: 15, value: -15 },
    { minute: 20, value: -30 },
    { minute: 25, value: -25 },
    { minute: 30, value: 15 },
    { minute: 31, value: 40 },
    { minute: 35, value: 25 },
    { minute: 40, value: 10 },
    { minute: 45, value: 5 },
    { minute: 50, value: -20 },
    { minute: 55, value: -35 },
    { minute: 60, value: -40 },
    { minute: 65, value: -30 },
    { minute: 70, value: -15 },
    { minute: 75, value: -25 },
    { minute: 80, value: -10 },
    { minute: 83, value: 5 },
    { minute: 85, value: -5 },
    { minute: 88, value: 35 },
    { minute: 90, value: 20 },
  ],
};
