import type { StandoutPlayerData } from "@/components/StandoutPlayerCard";

export const round8Standout: StandoutPlayerData = {
  name: "Nahir Besara",
  position: "AM",
  age: 35,
  nationality: "Sverige",
  rating: 9.8,
  matchName: "Hammarby 4-1 Malmö FF",
  matchDate: "17 maj 2026 · Omgång 8",
  minutes: 90,
  heroStats: {
    goals: 3,
    assists: 1,
    xG: 1.92,
    xA: 0.62,
  },
  highlights: [
    "Hattrick",
    "Skapade flest chanser (8)",
    "Hade flest skott (9)",
    "Betyg 9.8",
    "3 stora chanser skapade",
  ],
  topStats: [
    { label: "Mål", value: "3", highlight: true },
    { label: "Assist", value: "1", highlight: true },
    { label: "xG", value: "1,92", highlight: true },
    { label: "xGOT (på mål)", value: "2,36", highlight: true },
    { label: "xA", value: "0,62" },
    { label: "Skott totalt", value: "9" },
    { label: "Skott på mål", value: "4" },
    { label: "Skott utanför", value: "4" },
    { label: "Skapade chanser", value: "8", highlight: true },
    { label: "Stora chanser skapade", value: "3", highlight: true },
    { label: "Passningar", value: "37/45 (82%)" },
    { label: "Bollkontakter", value: "68" },
  ],
  seasonComparison: [
    {
      label: "Mål",
      value: "3",
      seasonAvg: "~0,4/match",
      multiplier: "7,5x",
    },
    {
      label: "xG",
      value: "1,92",
      seasonAvg: "0,24/match",
      multiplier: "8x",
    },
    {
      label: "Skott",
      value: "9",
      seasonAvg: "3,6/match",
      multiplier: "2,5x",
    },
    {
      label: "Skott på mål",
      value: "4",
      seasonAvg: "0,9/match",
      multiplier: "4,4x",
    },
    {
      label: "xA",
      value: "0,62",
      seasonAvg: "0,27/match",
      multiplier: "2,3x",
    },
    {
      label: "Skapade chanser",
      value: "8",
      seasonAvg: "~1/match",
      multiplier: "8x",
    },
    {
      label: "Bollkontakter",
      value: "68",
      seasonAvg: "~55/match",
      multiplier: "1,2x",
    },
    {
      label: "Passningar",
      value: "37 (82%)",
      seasonAvg: "37 (88%)",
    },
  ],
  tacticalNotes: [
    "Besara spelade som tia bakom Abraham och styrde Hammarbys kreativitet centralt – exakt den roll som beskrivs i positionsprofilen.",
    "Heatmap visar extrem aktivitet i höger halvrum och centralt i motståndarens 16-meterslinje – precis där GAIS släpper in mål.",
    "Skapade 8 chanser (lika med de bästa i hela Allsvenskan en enskild omgång) och hade direkt inblandning i alla 4 mål.",
    "xGOT 2,36 (= förväntad målvärde baserat på var skotten träffade) visar att Besara inte bara sköt ofta utan placerade bollen med precision.",
    "Trots hög offensiv output (9 skott) behöll passningstrygghet – 82% precision under en match där han sökte riskpassningar konstant.",
  ],
};
